### ISSUE TITLE
New Gravel sound

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#102]
See this commit for informations : https://github.com/Ombridride/minetest-minetestforfun-server/commit/2b937048105bafdc1fb2ab8a8ceb5ec2f08f784e

We need four gravel sounds :
- [x] Gravel sound 1
- [ ] Gravel sound 2
- [ ] Gravel sound 3
- [ ] Gravel sound 4

**Comment by ObaniGemini** [comment]
Fixed https://github.com/Ombridride/minetest-minetestforfun-server/commit/b38450dc0a5526dd242491e25cc013815bbf225a

**Comment by Ombridride** [comment]
Euh... t'as mis 4 fois le même ?

**Comment by ObaniGemini** [comment]
Il n'y en a que 2

**Comment by Ombridride** [comment]
Il en faut 4 __vraiment__ différent ;)

**Comment by ObaniGemini** [comment]
C'est ça de faire des trucs à 1h du mat' ;)

**Comment by gravgun** [comment]
Fixed in 3b4037a.

**Comment by Ombridride** [comment]
Great sounds, great work !
