### ISSUE TITLE
Update armors spreadsheet

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#103]
We need to add the __hunger exhaust__ values on the spreadsheet, everybody can do it, it's easy :)

The spreadsheet is available here https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/other_things/Tableau-valeurs-MFF.ods
And the value to enter available here https://github.com/Ombridride/minetest-minetestforfun-server/commit/9bf13e39657f51328d8cf81885857c58e24eb6f4

(PS : do something beautiful, it will be posted on the website)

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/6d05139bbb074e2cd995efeed6695e798f154416

**Comment by Ombridride** [comment]
It's good, the hearths has been moved by mistake, i have fix this issue...
