### ISSUE TITLE
Mobs issues

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#104]
### Wolf & Dog
The wolf is transformed in Dogs when we give to him 5 raw_meat, the problem is when we give raw_meat to wolf, the counter is incremented but the raw_meat isn't consumed (player side)

The other problem is when the wolf is tamed, the transformation is dog works BUT the dog isn't tamed by the player and just walk/run around his spawn point

### NPC
Follow you without stop... Can be tamed ? Very strange...

**Comment by crabman77** [comment]
Fixed meat_raw no consumed , dog owner
replace dog type monster by NPC, else dog attack player

https://github.com/Ombridride/minetest-minetestforfun-server/commit/a81ee9d530ebceb18c058000be845ae8aab36163

**Comment by Ombridride** [comment]
Ok, yes i forgot to tweak the damage parts, i do it right now

**Comment by LeMagnesium** [comment]
The NPCs are fine, except for one thing. A NPC follows you after you rightclicked it with 4 diamonds. It will look toward you, but only move when you right-click it again (kind of "unlocked" mode). When you rightclick it again, you stick it to the position it is at the moment (a sort of "locked" mode).
The only problem I noticed with NPCs are that diamonds aren't taken from players' inventories, I'm working on it.

**Comment by Ombridride** [comment]
Ok, we need to tweak news.txt to explain that point about NPC to in-game players

**Comment by LeMagnesium** [comment]
An information section could be added then.
https://github.com/Ombridride/minetest-minetestforfun-server/commit/a10892882031920eac16837d3b30b625d724a812
Can I close this now?

**Comment by Ombridride** [comment]
Everything is done
