### ISSUE TITLE
Freeze with the compassgps mod

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#106]
Initial message from JAPP in-game player : 
MinetestForFun, avec palige (qui pourra confirmer), j'ai utilisé la boussole... au début, rien de spécial mais ensuite, un freeze s'est provoqué. On a été obligé de se déconnecter (en attendant d'être déconnecté ensuite) et palige s'est connecté seul : aucun freeze... J'ai été obligé de jeter dans la trash ma boussole (#tristesse/#JeSuisBoussole)

So, the compassgps seems to freeze the server when used, we need to check this point as fast as we can

**Comment by LeMagnesium** [comment]
I don't think the freeze and compassgps are related, I've seen no freeze when using the compass.
