### ISSUE TITLE
Disk and SWAP space on MinetestForFun server

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#109]
#### Hard Drive Disk
- [x] The server is almost out of space, i need to add a 20GB more space for reach a 40GB of total space !
Add a more larger HDD is easy and jsut need 2 clicks, the problem is for the re-partitionning OS side of the system, i need to reboot the server with a Live Gparted OS, and move partitions needs times... (40 to 50 MB/s of writing on my dédibox)

#### SWAP
- [x] Same has the Hard Drive disk, the SWAP is added since a long time, but not tweaked with GPARTED live OS, it's a mistake since a very long time :/ (don't worry, the SWAP is nearly never used), i will __add a 8GB of SWAP space__ soon
- [x] Add ZSWAP/ZRAM from https://wiki.debian.org/ZRam

**Comment by Ombridride** [comment]
Everything is done right now, closed the issue

**Comment by Ombridride** [comment]
Re-opened, the ZRAM needs to have a more high priority than SWAP

Actually SWAP is -1 and ZRAM is ???

**Comment by gravgun** [comment]
The Debian script swapons zram0 with a priority of 10, so it's good already.

**Comment by Ombridride** [comment]
Great ! Thank you for this comment :)
