### ISSUE TITLE
Add the mod [inventory_icon]

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#110]
#### Official description of the mod
This mod shows a backpack icon at the bottom right of the HUD. It shows the number of free and maximum slots in your main inventory. The backback icon turns red when all slots are occupied.

![inventory_bag](https://forum.minetest.net/download/file.php?mode=view&id=2773&sid=31c56fcda4243dcf2a87cbb050a6060f)

There is also optional support for the bags from Unified Inventory. If this mod is used, additional bag icons (if bags are present) are displayed.

![inventory_optional_bag](https://forum.minetest.net/download/file.php?mode=view&id=2974&sid=8b4796402d321abd65910a896be15b85)

Note: Only the main inventory counts, other slots (such as crafting grid) are not counted.

Please report any bugs and weirdnesses and potential problems with the HUD! But hopefully, this mod should be relatively stable by now.

Dependencies: None!
Optional dependency: Unified Inventory [unified_inventory]
Code license: WTPFL
License of graphics: Overall: CC-BY-SA 3.0 Unported.

#### Link
https://forum.minetest.net/viewtopic.php?f=9&t=12358&p=180253#p180253

#### Other informations
No need to tweak this mod, integration with our hud and inventory(optional) is native.
We just need to place correctly the inventory bag / optionnal bags at the right place, maybe at the right of the current HUD ?

**Comment by gravgun** [comment]
Added in bba533ea74.

**Comment by Ombridride** [comment]
Great, the position of the bags are correct, thank you !
