### ISSUE TITLE
Textures and the new [throwing] mod

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#112]
We need to create 32px textures for every textures of the new implemanted _throwing_ mod 

#### Link to the textures folder
https://github.com/Ombridride/minetest-minetestforfun-server/tree/master/mods/throwing/textures

#### Textures map
- [x] throwing_arbalest
- [x] throwing_arbalest_loaded
- [x] throwing_bow_composite
- [x] throwing_bow_composite_loaded
- [x] throwing_bow_horn (already made by Obani)
- [x] throwing_bow_horn_loaded (already made by Obani)
- [x] throwing_bow_royal
- [x] throwing_bow_royal_loaded
- [x] throwing_bow_steel
- [x] throwing_bow_steel_loaded
- [x] throwing_bow_wood
- [x] throwing_bow_wood_loaded
- [x] throwing_crossbow
- [x] throwing_crossbow_loaded
- [x] throwing_longbow
- [x] throwing_longbow_loaded
- [x] bow_loaded => 32px arrow for loaded bows (already made by Obani)
- [ ] MAYBE ? bow_loaded => 32px arrow for loaded crossbows

#### Other informations
Try to keep the initial 16px design if you can, and adapt it to a 32px texture
For the arrow texture in loaded bows, Obani has already done a texture, so you can reuse it. But maybe you need to do an another arrow for the crossbow
Re-use the initial 16px texture or not isn't a requirement, you can use another texture from another place, or create a texture from scratch, but keep in mind the texture needs to be similar in certain points with the initial 16px texture.

**Comment by gravgun** [comment]
Work done.
