### ISSUE TITLE
Mods update needed

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#117]
#### Mods wich need to be updated/checked
- [X] bedrock2 https://forum.minetest.net/viewtopic.php?f=11&t=11271&view=unread#p170579
- [x] homedecor https://forum.minetest.net/viewtopic.php?f=11&t=2041
- [x] Stairs (mt_game) https://github.com/Ombridride/minetest-minetestforfun-server/commit/169327abceb04cafa8449bd69d14bad69a4021b4 https://github.com/Ombridride/minetest-minetestforfun-server/commit/42fcceec5b58c11fa0943e7f1aa27209d2f7f46e
- [x] Improve item_drop https://github.com/Ombridride/minetest-minetestforfun-server/commit/fc94c4f29a7ad245361b88194c3d37075f802c41
- [x] unified_inventory, voir si des choses à récupérer (attention notre version est hautement modifié) https://forum.minetest.net/viewtopic.php?f=11&t=12767
- [X] mapfix (déja update normalement, à checker) https://forum.minetest.net/viewtopic.php?f=9&t=10662 => https://github.com/Ombridride/minetest-minetestforfun-server/commit/f5ce1d3fb531e12c85206fccd5093c07b8133cba
- [X] mesecons https://forum.minetest.net/viewtopic.php?f=11&t=628
- [X] 3d_armor https://forum.minetest.net/viewtopic.php?f=11&t=4654 => https://github.com/Ombridride/minetest-minetestforfun-server/commit/e774ed402de0096bb8623bd0171029e7c98ef6e0
- [x] arrowsign https://github.com/Ombridride/minetest-minetestforfun-server/commit/322926fc5b1a09b5534b943c72ca3e19db476f1d
- [X] inventory icon (petite modif ficheir depend.txt pour le charger apres unified inventory) https://forum.minetest.net/viewtopic.php?f=11&t=12358&view=unread#p183746 => https://github.com/Ombridride/minetest-minetestforfun-server/commit/af4096f24e85b9087a2e073a36df7ed612a1ff9f
- [x] mobs 1.13, __I will do this update__ because the mobs mod is heavy tweaked https://forum.minetest.net/viewtopic.php?f=11&t=9917
- [X] solarmana (just update the API to add drain function and bugfixs) https://forum.minetest.net/viewtopic.php?f=9&t=11728&view=unread#p184116 => https://github.com/Ombridride/minetest-minetestforfun-server/commit/c10173888b5918dd7b67c2d619574e301260a9a1
- [x] farming redo (check if up to date)https://forum.minetest.net/viewtopic.php?f=11&t=9019&hilit=redo

**Comment by gravgun** [comment]
Note that in be03e62452fcd571554f6cf7d6739e2b502b8441 I and crabman changed the other_things/update_sources.txt to have a parse-able format (for a future script) and to be up-to-date.

**Comment by LeMagnesium** [comment]
The're nothing to update about bedrock2.

**Comment by Ombridride** [comment]
Ok for bedrock2 and homedecor_modapack, they are now checked.
Need to update/check oter mods

**Comment by crabman77** [comment]
unified_inventory a été mis à jour il y a 10 jours.(il n'est pas dans les news d'ailleurs)

**Comment by Ombridride** [comment]
Très bien coché, les ajouts n'étant pas visible, j'ai réduit les news au maximum :)
D'ailleurs, pourrais tu cacher les bouton jour/nuit pour les joueurs n'ayant pas le droit admin ?

**Comment by crabman77** [comment]
ils sont caché, chaque bouton est cacher si le le joueur n'a pas le privs associé, jour/nuit=set_time.

**Comment by Ombridride** [comment]
nickel, je ne me connecte plus très souvent en joueur ne n'avais donc pas remarqué

**Comment by LeMagnesium** [comment]
La mise à jour de mapfix consistait simplement en une modification du README: https://github.com/Ombridride/minetest-minetestforfun-server/commit/f5ce1d3fb531e12c85206fccd5093c07b8133cba

**Comment by LeMagnesium** [comment]
Rien à mettre à jour pour mesecons.

**Comment by Ombridride** [comment]
@LeMagnesium 
Je sais que tu t'en occupes personnellement presque à chaque fois. J'ai fait une MAJ du premier post, il manque donc les mods [solarmana] et [farming] (redo) à vérifier/mettre à jour

**Comment by Ombridride** [comment]
I closed the issue
