### ISSUE TITLE
Wateshed mapgen BUGS !

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#118]
- [x] Pas de minerais/presque aucun, urgent !
- [x] Trop d'eau ?
- [x] Trop de neige+glass en dessus/dessous de l'eau => Ok fausse alerte
- [x] Blocs blanc bizarres, généré proche de zone neigeuse appremment (pas considéré comme node, quand on pointe rien ne s'affiche, et ce bloc est transparent, on peut rentrer dedans, bug avec de la génération de bloc air ?)
![mapgen_bug](http://i.imgur.com/RNAcnft.png)
- [x] Supprimer le __Lux minerais__ et le remplacer par de la __stone__, pareil pour les items à base de __Lux__
- [x] Ajuster/supprimer la __sandstone__ dans les caves
- [x] augmenter le taux de __cactus__ sur la **desert_sand**

**Comment by Ombridride** [comment]
Bon point, mapgen très joli mis à part ces détails :
![screen](http://i.imgur.com/wm3fFBP.jpg)

**Comment by crabman77** [comment]
les blocs blanc bizarres, c'est des clouds je crois :)

**Comment by Ombridride** [comment]
Les clouds c'est parfois long et large mais pas haut de 30 à 40 blocs et ce n'est pas statique...

**Comment by Ombridride** [comment]
De plus les clouds sont bien là,  plus haut que ces zones bizarres....

**Comment by Gael-de-Sailly** [comment]
Pas de minerai ? Watershed génère les siens, mais c'est vrai qu'il ne fait pas ceux de moreores et compagnie. Je n'avais pas pensé à ça. Pareil pour les fleurs, les légumes, etc. On peut maintenant, depuis peu, générerer tous les minerais et les décorations dans un mapgen LUA, mais il faut être en 0.4.12.

Machins blancs ? c'est du default:cloud. C'est voulu par watershed. Si vous voulez, je supprime.

Trop d'eau ? C'est vrai que les océans sont gigantesques, mais les continents aussi. Peut-être la faute à pas de chance qu'on soit tombé dans un océan…
Essayez la graine "MinetestForFun" (13107546752813893513). En 0 ; 0 on se trouve au sommet d'une grande montagne. C'est sympa pour le spawn, non ?
Je propose de recommencer à nouveau à zéro une fois que tout ça sera corrigé, mais après je ne sais pas quelles contraintes ça t'impose.

**Comment by Ombridride** [comment]
oui agel supprime moi ces gigantesque zone de clous inutile, en plus quand t'es dedans, tu vois quand meme le dessous du de la zone en blanc...

pour les minerais, on a des valeurs perso, dans le **_game** node.lua de mémoire, il faudrait remettre ces valeurs dans le mapgen actuel, deplus il les valeurs nodes.lua de moreores sont soit dans le nodes.lua du _game, soit dans le mod moreores,

pour l'eau, on a besoin de vérifier, je ne suis pas sur qu'il y en ai "tant que ça"...

merci pour la graine, très bonne idée, le spawn en haut d'une montagne serait très beau ! (je l'avais deja mis hier soir sur une montagne d'ailleurs)

Oui, l'idée c'est de corriger vite les bugs et de reset, je vias rédiger les news + info aujourd'hui pour expliquer cela

**Comment by Gael-de-Sailly** [comment]
Aucun problème pour les minerais utilisant `minetest.register_ore`. Ils seront générés de la même manière que dans le v6, et avec vos paramètres, juste en ajoutant cette ligne : `minetest.generate_ores(vm, minp, maxp)` (en plus de ceux générés par watershed, dites-moi si je dois les supprimer ou pas). Attention : il faut que le serveur soit en 0.4.12, je ne sais pas si c'est le cas.

Un petit problème se pose avec darkage, qui génère ses minerais différamment, j'ajouterai la dépendance "watershed" pour être sûr que ses minerais se génèrent après le terrain de watershed.

**Comment by Ombridride** [comment]
A la limite, on fera des ajustements de minerais plus tard pour encourager les joueur à grimper les montagne (exemple, ajouter diamant/mese en hauteur, emse un peu plus, et diamant, parfois)

Donc pour l'instant : supprimer la génération de watershed, et ajouter notre ancienne généraion au mapgen de tel sorte que l'on ai la génération que j'ai paramétré auparavant

Je te laisse faire les commits, s'il te plaît :)

On est bien en 0.4.12-stable, attention pas dev, mais je pense que ça passera, j'ai pas souvenir d'avoir vu des modifs en -dev récemment,

OK pour darkage, je te laisse gérer !

**Comment by ObaniGemini** [comment]
Pour les minerais : ils n'apparaissent qu'en surface : j'ai trouvé du fer et du mese sur la montagne dont a parlé @Ombridride . Au niveau des océans géants je ne trouve pas que cela soit un problème car très souvent les continents sont aussi très grands et se rapprochent les uns des autres afin de pouvoir passer d'une rive à l'autre facilement.

**Comment by Gael-de-Sailly** [comment]
Voilà
J'ai fait quelques bêtises en poussant mes modifications, j'espère qu'il n'y a rien de grave.
Est-ce que ça vous convient ces dernières modifs ?

**Comment by Ombridride** [comment]
On va reset le world et testé avec tes dernières modifs @Gael-de-Sailly, meric pour ton travail efficace et rapide !

**Comment by Ombridride** [comment]
Le mapgen est maintenant correcte, on le garde tel qu'il est actuellement, tout semble fonctionnel (tesé queqlues heures hier soir)

**Comment by Ombridride** [comment]
Re-opened because we have finf many craft recipe wich isn't removed, like the "watershed:lux", we need to fix it quickly, thank you !
(it's maybe special minerals generated by the watershed mod ? Need to check it)

**Comment by Gael-de-Sailly** [comment]
The Lux ore is a special ore generated by the watershed mod. It's used to craft (ugly) lamps. I'll change the textures, remove some craft recipes, and reduce the amount of lux crystals given by one block (for now that's 8 per block !). I'll do it tomorrow morning.

Another problem : some trees that haven't a trunk !
[watershed/functions.lua](https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/mods/watershed/functions.lua), 119 first lines. I don't understand why some trees have not a trunk. It happens with the 3 trees.

**Comment by ObaniGemini** [comment]
I found a lux ore mine.... It's infinite xD

**Comment by Gael-de-Sailly** [comment]
Another problem : no junglegrass !

**Comment by Ombridride** [comment]
For this three trees bugged, you can use the default mapgen code

**Comment by Ombridride** [comment]
Re @Gael-de-Sailly 
Ce soir, je remarque avec @crabman77 qu'il y a beaucoup trop de __sandstone__ dans les caves.
Je pense qu'il faudrait régler cela en remplaçant la __sandstone__ par de la stone _d'un coup_ à partir de __x, -1024, z__

**Comment by Ombridride** [comment]
/!\ Beaucoup trop de sandstone dans les caves, deplus la sandstone ne contient _pas_ de minerais /!\

**Comment by gravgun** [comment]
8f0c33c608f09a13fcce8ac179c5391664eae8d3

**Comment by Ombridride** [comment]
Nickel, je clos... Jusqu'à de nouvelles aventures avec le mapgen :D

**Comment by Ombridride** [comment]
<MinetestForFun> je vois bien des cactus c'est bon
<MinetestForFun> il y en a suffisemment sans en avoir trop, on est bon
<MinetestForFun> ok, je vois de la sandstone entre -80 et -100
<MinetestForFun> -200 et -220
<MinetestForFun> -300 et -320
<MinetestForFun> -470 et -490
<MinetestForFun> -520 et -540
<MinetestForFun> bon, il y en a bien moins qu'auparavant
<MinetestForFun> mais il en reste

**Comment by Gael-de-Sailly** [comment]
Je donne mon avis sur la sandstone :
Je l'aime bien à la surface, c'est beau et ça change de la roche grise, par contre quand on mine c'est vite énervant. Donc je propose de la garder en surface jusqu'à -50 ou -100, et de la supprimer plus bas.
@gravgun a fait le contraire : est-ce que c'était l'effet voulu ou une erreur ?

Il faut savoir une chose : la profondeur à laquelle on la trouve n'est pas constante du tout.
Je peux m'en occuper aujourd'hui si vous êtes d'accord.

**Comment by Ombridride** [comment]
Je suis d'accord, gardons là en -50 a -100 ça fait de la diversité, et virons là plus bas, ça encouragera les joueurs a creuser plus bas

**Comment by gravgun** [comment]
@Gael-de-Sailly @gravgun aimerait te dire que tu regardes un commit déréférencé, le bon et l'actuel est 7a758082e2a780405bce237a2b9b00d09cd001a3, qui lui est correct.

**Comment by Ombridride** [comment]
gravgun, nous avons toujours de la sandstone de généré, il doit de manquer une potion de code quelque part...

**Comment by Gael-de-Sailly** [comment]
Pour moi tout est bon :)
J'ai testé, je n'ai pas trouvé de sandstone en-dessous de -84.
Essayez avec la minimap, c'est flagrant.

@gravgun a fait tout ce que je voulais faire :)
tant mieux parce que j'en ai un peu marre de travailler sur ce mapgen :p

**Comment by Ombridride** [comment]
Ok parfait, je referme cet issue ducoup
