### ISSUE TITLE
Mobs Debug thread

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#119]
Last merge since right now with the repository and the mobs still doesn't work correctly....
 
#### Dog
- [x] The following is too close from the players (need a 1 or 2 node space, I think)
- [x] Tamed with raw_meat
- [x] Raw_meat isn't consumed for tamed Wolfs to Dogs
- [x] The tamed feature is great, but the dog sometimes doesn't follow the played when it appears, it needs a cup a second before follow the player, maybe improve the code ?
- [x] Raw_meat (dog health restoration) isn't consumed => /!\ need to check this /!\

#### NPC
- [x] The following is too close from the players (need a 1 or 2 node space, I think)
- [x] Tamed with diamonds
- [x] Diamond isn't consumed for tamed NPCs
- [x] The tamed feature is great
- [x] Bread (NPC health restoration) isn't consumed
- [x] The NPC doesn't follow diamonds

**Comment by crabman77** [comment]
Fixed Diamond isn't consumed for tamed NPCs
Fixed The NPC doesn't follow diamonds
https://github.com/Ombridride/minetest-minetestforfun-server/commit/64ff46066873e82e9d924a0a674aafb62a4fa50e

**Comment by Ombridride** [comment]
Ok, thank you, i've updated the first post, can you check the last points please ?

**Comment by crabman77** [comment]
Bread (NPC health restoration) isn't consumed --> work

 
The following is too close from the players (need a 1 or 2 node space, I think), --> 2 to 4

https://github.com/Ombridride/minetest-minetestforfun-server/commit/c366a481ead855100f5852a18e6d3e75ad567cab

**Comment by Ombridride** [comment]
Great job, everything is ok, i closed the issue
