### ISSUE TITLE
Missing textures / useless call

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#125]
When you're just connecting to the server, you can see two textures missing :
![missing_textures](http://i.imgur.com/v7JgzxK.png)

**Comment by crabman77** [comment]
Fixed https://github.com/Ombridride/minetest-minetestforfun-server/commit/525ecd997536f752cefc9e4f685878e3be2d5b1a

**Comment by Ombridride** [comment]
Ok you add the **watershed_cloud** texture, but your code still take the **default_cloud** texture, normal ?
https://github.com/Ombridride/minetest-minetestforfun-server/commit/24b398aa1047af27edddd74b530938d06fed784b#diff-45ba29edb84c5838e02ebe6267c0621fL57

**Comment by crabman77** [comment]
No, first time I added watershed_cloud.png, but after I reverified in code, he rewrited default:cloud but with watershard_cloud.png texture.
So I removed texture and changed in the code.

**Comment by Ombridride** [comment]
Ok, thank you for your explanation
