### ISSUE TITLE
nether no generate in singlenode

### ISSUE THREAD

**Issue by crabman77** [Ombridride/minetest-minetestforfun-server#130]
Watershed mod set mg_name in singlenode, nether no generate in singlenode.
Maybe @HybridDog  have fix?

![capture-14](https://cloud.githubusercontent.com/assets/7189389/8704435/3c225fd0-2b23-11e5-9fbd-8b162ce46b62.png)

**Comment by Ombridride** [comment]
We have re-activated our LUA mapgen (watershed modified version) below -19600, so th nether is now correctly generated :)
The singlenode is something strange...

**Comment by Gael-de-Sailly** [comment]
@crabman77 has reported some mapgen problems in the nether, like this one :
![nether mapgen bug](http://img11.hostingpics.net/pics/570030screenshot20150716151440.png)

I've tested in singleplayer 2 hours ago with latest MFF code and I haven't found this kind of problems :)
Could someone else test it please ?

**Comment by HybridDog** [comment]
>Watershed mod set mg_name in singlenode, nether no generate in singlenode

adding watershed as an optional dependency to the nether mod's depends.txt might fix the problem

>has reported some mapgen problems in the nether, like this one

l think minetestforfun game didn't merge the bug fixes.

**Comment by Ombridride** [comment]
Ok, thank you for your intervention @HybridDog ! :)

#### Fix our problem about the nether mod

- [ ] Adding watershed as an optional dependency to the nether mod's depends.txt
- [ ] Update the nether mod (because it includes bugfixes we need)

**Comment by Ombridride** [comment]
Everything is ok, i closed the issue
