### ISSUE TITLE
Life regeneration

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#131]
#### Check hud mods
We need to check the hud mods to investigate about the health regeneration.

- Is the life regeneraiton always activated ? 
- With wich number of hunger ? 
- With wich number of hunger the regeneration is desactivated ?

**Comment by gravgun** [comment]
`hbhunger` is the mod responsible of the hunger bar's display (`hunger.lua` mainly) as well as health restoration and hunger damage (globalstep-registered function in `init.lua:100`). The current values are as follows:
* The hunger HUD update tick rate (`HUNGER_HUD_TICK`) is currently `0.1` s
* The max number of food points is 30 (constant, `init.lua:70`)
* The hunger/health computation is triggered each `4` seconds (constant) or `HUNGER_HUNGER_TICK` seconds. To heal the player (1 HP), satiation must exceed 15 points (constant). If is is lower or equal to 1 (constant), a health point is taken.
* `HUNGER_HUNGER_TICK`, the rate at which a hunger point is taken, is currently `800` s

**Comment by Ombridride** [comment]
Ok,
- [ ] Set __HUNGER_HUD_TICK to 1.0 second
- The max number of food is good
- [ ] Set the hunger/health computation to 10 seconds
- The HUNGER_HUNGER_TICK is ok, the value to 800 is ok for standing player without do nothing. The armor exhausting value and other exhausting things (walk/dig) are great for improve the realism of the satiation.

Thank you for your time gravgun ;)

**Comment by gravgun** [comment]
@crabman77 and I talked a bit on IRC about the sad state of the hunger system and how it tucks itself in the existing food callbacks, and how it's actually inflexible. This also applies to other stats and their respective bars, such as mana/magicka and stamina.
What I suggest (and @crabman77 will probably agree) is basically to throw out the existing mods (`hbarmor`, `hbhunger`, `sprint`, `mana`) as we have only little *code* relying on it (the only mana-using thing I know is the recently-introduced broomstick) and create a more generic, flexible, unified and universal (i.e. usable by other mods and subgames (not only us; maybe create it in another repo and use git submodules), possibly with an API compatibility layer for existing `mana`-relying mods) API under a name like `playerstat(u)s`, with hookable/overridable actions in a non-hacky style, and if possible, arbitrary statuses (try to find a way to bind to a variable, Lua has no C-like pointers but we can take huge advantage of `table`s being references) with arbitrary modifiers.
It won't display the stat bars by itelf, it will depend on the already-universal `hudbars` mod for this.
This task can, probably, likely, **will** be a blocker for #113, #114, and @LeMagnesium's [pclasses] mod (although its basic mechanism can be developed independently).

Unless you oppose this, I will open an issue ticket tracking the creation of such a mod

**Comment by gravgun** [comment]
1cb9500 Raised the rick rate to 1s.
However I've let the computation rate to the 4s constant because that would mean 2.5x slower life regen, which unless you explicitly state so, I won't let happen.
Letting the issue open for further discussion about the playerstat[us] mod and further decisions.

**Comment by Ombridride** [comment]
Yes, set the Set the hunger/health computation to 10 seconds :
- [ ] Set the hunger/health computation to 10 seconds
(the life regeneration for hunter/wizard need to be slow, the warrior will be the only with his shield regen to have a hug life regeneration, the another point is the health spells wich will come before the wizard...)

**Comment by gravgun** [comment]
cbba955

**Comment by Ombridride** [comment]
Thank you, i closed the issue
