### ISSUE TITLE
Axes break instantly when digging melon using them

### ISSUE THREAD

**Issue by Calinou** [Ombridride/minetest-minetestforfun-server#133]
If you use an axe (tested with Mese Axe) to dig melon, it breaks instantly, even if it's brand new.

**Comment by crabman77** [comment]
I think invtweak has a bug, last week my hand broken.

**Comment by Ombridride** [comment]
Lol ! Indeed we need to investigate :/

**Comment by Ombridride** [comment]
Same thing with the admin pickaxe, i digged dirt with grass...

**Comment by LeMagnesium** [comment]
The admin pickaxe does not use any kind of dig system, but punch. __This is not normal.__

**Comment by crabman77** [comment]
It's mobs by @tenplus1 which introduces the  admin pickaxe wear bug, https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/mods/mobs/api.lua#L1135

**Comment by Ombridride** [comment]
Ok, we need to fix first the __mobs__ mod used tool bug...

**Comment by crabman77** [comment]
I think it's fixed https://github.com/Ombridride/minetest-minetestforfun-server/commit/37d5883c41e53696604f935cf201dfaf0b38bd8b

**Comment by Ombridride** [comment]
I closed the issue. It will be re-opened if the problem is still here.
