### ISSUE TITLE
Watershed mapgen BUGS ! #2

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#136]
#### Other bugs need to be checked/fixed about the watershed new mapgen

- [x] The papyrus isn't generated on the new mapgen => after check, yes they spawn
![papyrus_new_mapgen](http://i.imgur.com/yFvoxWB.jpg)
- [x] The papyrus needs to be generated and grow on **default:dirt_with_grass**, **default:dirt**, **default:sand**, **default:desert_sand**
- [x] pyramids spawn in a way very strange and bugged...
![pyramids_bug](http://i.imgur.com/P5p03SR.jpg)
And generated underground ?!
![underground_pyradmid_bug](http://i.imgur.com/q34Smh8.png)
Is cutted if exceeds +110 ?
![pyramids_110+](http://i.imgur.com/oytta1L.png)
- [x] I can see many small ships underwater, but i haven't see big ships(created with tree_trunks/planks), need to check this point https://github.com/Ombridride/minetest-minetestforfun-server/commit/e3ba9bb197eb8cb5faf4bad7ab68fc334af5da60

@crabman77 @gravgun @Gael-de-Sailly, if someone can check this little point ? Thank you in advance
@Wuzzy2 will maybe be interrested about his [pyramids] bugs with the [watershed] lua mapgen

**Comment by Cyberpangolin** [comment]
I can confirm the papyrus grows on dirt only.

**Comment by Gael-de-Sailly** [comment]
Je veux juste vous rappeler que je ne suis pas disponible avant une semaine, c'est probablement ma seule connexion à Internet avant le 1er août.
Je suis désolé mais vous devrez vous en occuper vous-mêmes.

**Comment by Ombridride** [comment]
Pas de soucis @Gael-de-Sailly !

@gravgun, @crabman77 => vos dernières modifications ont elles réparé le bugs des pyramids ?

**Comment by crabman77** [comment]
aucune idée, je n'ai rien modifié.

**Comment by gravgun** [comment]
@Ombridride 41b34841021efc63b8626ac62bad763ed21a6155 delayed Pyramids generation, which will most likely fix the current issues as I guess they're related to timing (since the code is pretty clean). The only "bug" that's actually a(n "overexpressed") feature is pyramids generating underground.

**Comment by Ombridride** [comment]
Everything is ok, closed this issue
