### ISSUE TITLE
Don't protect mesecons gates ?

### ISSUE THREAD

**Issue by paly2** [Ombridride/minetest-minetestforfun-server#137]
I know that the drop of the mesecons logics gates is a protection against server overload.
But this protection prevents the use of gates, because they break quickly. We need to replace them by luacontrollers...
I propose to comment the lines 30, 31 and 32 of the mesecons_gates init.lua file. So, the gate isn't drop (but the condition rest).

**Comment by Cyberpangolin** [comment]
I think it's safer to have such a protection. Maybe it's better to multiply 10x the limit or something like that? They would be harder to break, but it could still happen before a server crash. :P

**Comment by Ombridride** [comment]
We can improve the limit, but x10... It's too big...

**Comment by paly2** [comment]
Maybe 3x ?
note : To change this value, you can just add (or set if it already exists) the "mesecon.overheat_max" value in the minetest.conf (the default value is 20).

**Comment by Ombridride** [comment]
Set for the next reboot : 

```
# MESECONS_MOD - paramétrage des outils logiques
mesecon.overheat_max = 60
```

I closed the issue.
