### ISSUE TITLE
Mobs bugs/tweaks

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#138]
#### Bugs/tweaks about monsters/animals

- [X] The cow animlal doesn't become agressive anymore when you attack them => the mobs .lua code seems to be ok https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/mods/mobs/cow.lua#L7 => **Cows become aggressive, the current lag just delays the action a bit** (Mg)
- [X] The warthog animal doesn't become agressive anymore when you attack them => the mobs .lua code seems to be ok https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/mods/mobs/warthog.lua#L7 => **Same problem as the cows** (Mg)
- [X] The goat animal doesn't become agressive anymore when you attack them => the mobs .lua code seems to be ok https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/mods/mobs/goat.lua#L7 => **Same problem as the warthog** (Mg)
- [X] The Big/medium/small Green Slime monster have a knockback, we need to remove it https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/mods/mobs/greenslimes.lua#L140 => The knockback is already set to 0, but the jump of the mob is again "stopped" when we attack him... => **See below** (Mg)
- [X] The Big/medium/small Lava Slime monster have a knockback, we need to remove it AND add a lava_bucket drop for the Small Lava Slime https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/mods/mobs/lavaslimes.lua#L147 => The knockback is already set to 0, but the jump of the mob is again "stopped" when we attack him... => **Same for all the slimes, and all monsters with little jumps. We can't do anything, it's from the engine.** (Mg)
- [x] The Creeper monster have a too bigknockback, we need to reduce it => the default knockback was modified accidently to 3, now re-set to 1, so this tweak isn't needed https://github.com/Ombridride/minetest-minetestforfun-server/commit/07f78821fe85888a7d35314b041c241298c2cdbd
- [x] Add super_apple drops to the Tree Monster https://github.com/Ombridride/minetest-minetestforfun-server/commit/07f78821fe85888a7d35314b041c241298c2cdbd
- [X] 27/07/15 => the hitbox of the __cow__ animal isn't good anymore, need to make it bigger and rectangular => https://github.com/Ombridride/minetest-minetestforfun-server/commit/f0ace0faad4a87f6efe6bf1e60bece933ebd9291

**Comment by Ombridride** [comment]
@TenPlus1, maybe are you interrested about the bug of the Slimes ?
The Big Slimes "stop" their jump when we attack them, even if the knockback is set to 0

**Comment by crabman77** [comment]
0 mobs uses "group_attack".
> /mobs $ grep group_attack *.lua
> api.lua:	group_attack = def.group_attack or false,
> api.lua:	if obj.group_attack == true and obj.state ~= "attack" then


do_attack don't verify if tamed?
https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/mods/mobs/api.lua#L83

**Comment by Ombridride** [comment]
https://forum.minetest.net/viewtopic.php?f=11&t=9917&p=185520#p185509

**Comment by LeMagnesium** [comment]
New hitbox for the cows : 
![Cows' hitbox](https://lut.im/T9rHyDuJ/OJoGvIFl)

**Comment by Ombridride** [comment]
Great ! :)
