### ISSUE TITLE
[mobs] Floating eggs

### ISSUE THREAD

**Issue by LeMagnesium** [Ombridride/minetest-minetestforfun-server#141]
This issues is related to our revision of @tenplus1 's [mob](https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/mods/mobs).
Players recently saw these floating eggs above our map's landscape :
![screenshot_20150720_185718](https://cloud.githubusercontent.com/assets/6785985/8784174/df047c3c-2f20-11e5-873f-29ac0b3e03db.png)

### To fix : 
 - Avoid putting eggs when no block is above

### Ideas
 - Check the chicken's velocity?
 - Check whether or not a node is above the egg's hypothetical position?

**Comment by Ombridride** [comment]
Closed because fixed https://github.com/Ombridride/minetest-minetestforfun-server/commit/6ddba5a15e18be3ea080a33454759350cb9acd4d
