### ISSUE TITLE
Add craft for money system

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#142]
#### Need this crafts

- [ ] 9 copper coins => 1 silver coin
- [ ] 9 silver coins => 1 gold coin

and 

- [ ] 1 gold coin => 9 silver coins
- [ ] 1 silver coin => 9 copper coins

(ps : put it in the [maptools] mod)

**Comment by LeMagnesium** [comment]
I think it's a pain to have a 9-based numerical system, however, this is the easiest one for us to implement.
https://github.com/Ombridride/minetest-minetestforfun-server/commit/278611d9f3b63cbd937a494ba07ee0ccdb49889d

**Comment by Ombridride** [comment]
Not a problem at all
