### ISSUE TITLE
automappercolors

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#146]
#### Missing on the webmapper

- [x] We can't see flowers anymore on the mapper !

**Comment by Ombridride** [comment]
For the last color changes, i think the dirt_with_grass is just a bit too light, but it's not very important :)

And for the ocean water, this is a really problem... The color you set is cartooned and not transparent, now we can't see underwater...
Please, take our old ocean water color/transparency, they was great !

**Comment by gravgun** [comment]
Argh, indeed it's too light, and the ocean water isn't transparent any more, gotta fix the script again...

**Comment by Ombridride** [comment]
Now fixed https://github.com/Ombridride/minetest-minetestforfun-server/commit/a9f2f4c66dbb9cef8d551e817b5f634471d4632e

I closed the issue.
