### ISSUE TITLE
cooking clay is sloooow!

### ISSUE THREAD

**Issue by Cyberpangolin** [Ombridride/minetest-minetestforfun-server#147]
You need 9 clay bricks to make 1 brick block; it means that you need to cook 9 clay. The current cooking we have seems not to be the fastest. I've had ~400 brick blocks done with 6 furnace in one hour, which means that having enough clay bricks is very slow...

Maybe someone can investigate and accelerate it, for a better gameplay :)

**Comment by Ombridride** [comment]
thank you for this issue, you're right we need to reduce the "burning_time" of the clay !

So, i suggest to divided the burning_time per 4 (60min => 15min)

**Comment by LeMagnesium** [comment]
There is no such value as a burntime for an input item, we can't reduce it. Only fuels have those values. What fuel were you using?

**Comment by Ombridride** [comment]
the burntime for clay(and other minerals)is taken from the burned fuel ?!

**Comment by crabman77** [comment]
No, we must add "cooktime = *"

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/5efa99ee3060e90ac355517f20b4064f049502e6

**Comment by Ombridride** [comment]
The cooktime is now set to 2 seconds

We also find a mistake on the clay "max_stack" value, we re-set it to 200 (99->200)

Thank you for your issue !
