### ISSUE TITLE
Mapfix kills the server

### ISSUE THREAD

**Issue by Cyberpangolin** [Ombridride/minetest-minetestforfun-server#148]
Steps:
1) type /mapfix 50
2) it works fine
3) try with 200. it works fine again, but very slowly. You will have ~40 seconds lag.
4) try with more (1000?). You immediately kill the server.

--> a maximum value must be set, probably at 75.

**Comment by mgl512** [comment]
Il y a une limite pour les joueurs qui n'ont pas le privilege "server" : 50. les autres peuvent le casser si ca leur plait. 

Le_Docteur

**Comment by crabman77** [comment]
60 me kill le serveur :)

**Comment by Ombridride** [comment]
what ? you can set more than the value 50 ingame cyber ?!

**Comment by Ombridride** [comment]
The mod is now limited, the settings are in the minetest.conf

```
# MAPFIX MOD - Recalculate the flowing liquids and the light of a chunk
mapfix_default_size = 40
mapfix_max_size = 50
mapfix_delay = 15
```
