### ISSUE TITLE
Water bug

### ISSUE THREAD

**Issue by Cyberpangolin** [Ombridride/minetest-minetestforfun-server#149]
Sorry for reporting so much bugs...

I can see at least 2 types of water, maybe 3. They cannot mix together and have different colors.

-> Ocean water
-> River water
-> melted snow (not sure, while that water "lives" a very short amount of time)
Melted ice seems to be ocean water.

There should be one water only. Or, at least, they should fit together.

![capture du 2015-07-22 19 55 15](https://cloud.githubusercontent.com/assets/12512762/8832963/4f61d4ac-30ac-11e5-880f-f4b6a50f9e19.png)

**Comment by Ombridride** [comment]
"melting snow" have the same texture as the "ocean water" : yes
the special texture of the "river water" is normal
also, the different "sources_water"/"flowing_water" are normal...

the "melting snow" you pointed, is just a flowing water, not a source, so it disappear really fast

So, i don't see any bugs is this issue :)

It's great to see some players report bugs, thank you very much and do NOT hesitate to post another issues :)
