### ISSUE TITLE
2 different ways to get steel rails

### ISSUE THREAD

**Issue by farfadet46** [Ombridride/minetest-minetestforfun-server#154]
Currently there are 2 ways to craft steel rails:
X=Steel
O=wood stick
```
X X
XOX
X X
```
And another one:
```
XOX
XOX
XOX
```
The second one is using `stick`-group items rather than `default` sticks.
We must keep only one, but decide on which recipe we keep, given the second one is a tad more expensive but has the advantage of being crafted more easily (if one has multiple wood types).

**Comment by Ombridride** [comment]
The craft recipe with 3 sticks and the group:stick in its recipe is keeped, the other is removed https://github.com/Ombridride/minetest-minetestforfun-server/commit/366c2c3ea8654d97a7ce4d8dc79c098703d1ca48

Thank you for your report
