### ISSUE TITLE
pclasses crash

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#156]
01:36:18: ERROR[main]: ERROR: An unhandled exception occurred: caught (...)
<crabman> 01:36:18: ERROR[main]: stack traceback:
<crabman> 01:36:18: ERROR[main]:  [C]: in function 'is_empty'
<crabman> 01:36:18: ERROR[main]:  /var/opt/minetest_stable/bin/../mods/pclasses/init.lua:142: in function 'does_wear_full_armor'
<crabman> 01:36:18: ERROR[main]:  /var/opt/minetest_stable/bin/../mods/pclasses/init.lua:158: in function 'determination'
<crabman> 01:36:18: ERROR[main]:  /var/opt/minetest_stable/bin/../mods/pclasses/init.lua:215: in function 'func'
<crabman> 01:36:18: ERROR[main]:  /var/opt/minetest_stable/bin/../builtin/game/misc.lua:19: in function </var/opt/minetest_stable/bin/../builtin/game/misc.lua:9>
<crabman> 01:36:18: ERROR[main]:  /var/opt/minetest_stable/bin/../builtin/game/register.lua:341: in function </var/opt/minetest_stable/bin/../builtin/game/register.lua:329>

**Comment by crabman77** [comment]
Fixed https://github.com/Ombridride/minetest-minetestforfun-server/commit/0abe0a857ffa1a31ec6a7192c4b29af951a44811
