### ISSUE TITLE
Boat usebug

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#160]
Many players use the boat to attack monster safely, we need to fix this ! (or reduce its easy utilisation...)

- Forbidden the left click when in a boat ?
- Forbidden put a boat in an another location than the water_source and river_source ?
- any other ideas ?

**Comment by gravgun** [comment]
Some notes on your current ideas:
(1) would make players vulnerable and likely make them unable to escape monsters
(2): disallowing sailing on non-source nodes would defeat the boat's purpose for many player-built waterways as well as natural structures such as rivers

**Comment by ObaniGemini** [comment]
Boats would work on water_flowing. The only thing that would be modified would be the fact to be abled to pos it on water_flowing.

**Comment by crabman77** [comment]
Fixed :)   https://github.com/Ombridride/minetest-minetestforfun-server/commit/086942329e63b6dba0c7a12dd04223508d85ebc9

**Comment by Ombridride** [comment]
Thank you @crabman77 !
