### ISSUE TITLE
Water invincibility usebug

### ISSUE THREAD

**Issue by ObaniGemini** [Ombridride/minetest-minetestforfun-server#164]
This is a usebug that I use very oftently. If you go under water surface, you're unkillable by monsters.

**Comment by Ombridride** [comment]
Soon we will have sharks wich eat you in water :p

But this usebug still interresting for out-water mobs

**Comment by LeMagnesium** [comment]
It's not an usebug, it's just that mobs can't punch through water. You can't do anything about that. Just wait for the sharks.
