### ISSUE TITLE
Multiples fonctions manquantes dans mobs/api.lua

### ISSUE THREAD

**Issue by LeMagnesium** [Ombridride/minetest-minetestforfun-server#34]
Suite au merge de creeper et kamicaze dans mobs, de nombreuses fonctions inconnues ont été ajoutées. Parmi lesquels : 
`do_tnt_physics`
`activate_if_tnt`

Il me faudrait une explication plus précise de @davedevils , car pour merger j'ai dû enlever les fonctions mais je n'ai pas idée de ce qu'elles devaient faire.

**Comment by davedevils** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/pull/35

**Comment by LeMagnesium** [comment]
C'est réglé.
