### ISSUE TITLE
infinite world (no map limits)

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#50]
The worldedge mod teleports the player to the other side of the world when they reach the edge. 
When the player walks past 30000 in any direction they will be teleported to the other side of the world as if they walked around the world. (when you teleport to the other side you will be at ground height)

So, no worldmap limits can be reached ! :)

mod Link : https://forum.minetest.net/viewtopic.php?f=9&t=10753

(PS : We have the time for this mod, see below the actual worldmap)
![Actual WorldMap](http://i.imgur.com/o6W3xfN.png)

**Comment by LeMagnesium** [comment]
> (PS : We have the time)

Just enough time for me to add it, tomorrow. This mod seams great, I would like to see it. Does it work with every axis (x, y, and z)?

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/4d30bdcd61796d579d0fa5c031b33ca6eac3467e
