### ISSUE TITLE
Add "compassgps" mod

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#53]
The CompassGPS mod creates a customizable compass with user settable bookmarks and shared and admin bookmarks in multiplayer. We can also make and distribute unique maps for events like "treasures hunts", it's very funny !

The administrator can also teleport him to the bookmarked locations

We are going to implement this mod when we have time : https://github.com/Kilarin/compassgps

(Main Formspec)
![Main Formspec](https://camo.githubusercontent.com/8c6d2309161e652dd7c5d018a790dd2fe2d1e049/687474703a2f2f6936312e74696e797069632e636f6d2f613562376c692e706e67)
(Choose your Compass HUD texture)
![Choose your Compass HUD texture](https://camo.githubusercontent.com/22af69d5270ad8ccb46404e8b28388de1e90af19/687474703a2f2f6935392e74696e797069632e636f6d2f6161687161382e706e67)
(GPS position display)
![GPS position display](https://camo.githubusercontent.com/3017873dfc0892ce24601440fa6c15ae3ad99b26/687474703a2f2f6936302e74696e797069632e636f6d2f6661637765612e706e67)

Be carful : Don't forget to tweak the world.mt

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/41d3e2f68488190148bc3878b1b0a08f7908b3b1

**Comment by Ombridride** [comment]
We need to check the bugfixs available here, and check if it's usefull to add it to our server : https://forum.minetest.net/viewtopic.php?f=11&t=9373&hilit=punch&view=unread#p178842

**Comment by LeMagnesium** [comment]
I used today's version of the mod, the bugfixes are in it...

**Comment by Ombridride** [comment]
Perfect, i closed the issue.
