### ISSUE TITLE
Improved whoison mod

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#55]
We need to improve this mod, because it's not enought accurate !

Sample exit of the mod at this moment : "_player_ is online more than 2 weeks" (for a played time of 2week 6 days, 23hours...)
We need an exit like :  "_player_ has a total playing time of YY/MM/DD/HH/MM/SS" (Year/Mounth/Day/Hour/Minute/second)

We also need the alias  "/played <player>" for the command "/timeonline <player>", and if the player name is not specified, take the played time of the player who did the command

**Comment by LeMagnesium** [comment]
By rewriting this mod I can easiliy create such a precise mod. I will do this quickly.

**Comment by Gael-de-Sailly** [comment]
I could do it also. But I will not have the time before Friday.

**Comment by Ombridride** [comment]
I know but don't worry @Gael-de-Sailly the rewriting is begin. You can help @LeMagnesium if you want :)

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/0a18b1255e35aa318588af11ea055f91a92c1022
Should be enough, the rest of the code is working properly.

**Comment by Ombridride** [comment]
Finally ! Good work Mg ! :) (it doesn't crah the server anymore if you se the command ?)

**Comment by LeMagnesium** [comment]
Knowing that I added this on May 22th, and I fixed it the following day, it won't crash, and you've maybe already used it.
