### ISSUE TITLE
Add the [Warps] mod

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#56]
### Presentation :

This is a fairly simple warp mod, designed to make it easy for novice users to travel around a map without having to type in text commands, but without granting users permission to teleport to any location on the map.

Warps are created by the warp admin. Warp privilege needs to be granted to users (not enabled by default). The user can list and warp to the warp locations that exist.

Warp stones are available with /give and through a creative inventory. These stones work as one-way teleporters that can be programmed with a target by the warp_admin. No privileges are needed to use these warp stones. Users can't reprogram the target, only use it to warp. Users can also call the /warp command directly if they know the name of the warp location.

While warping, the user needs to stand still in one location for 5 seconds. This prevents combat escape and teleport overuse, as teleporting can cause large amounts of blocks to be loaded.

![Warp teleporter](http://i.imgur.com/pYv3xhN.png)

### Tweaks we need : 

- [ ] Add the [Warps] mod
- [x] Allow commands only for admins (this mod is too powerfull for "normal users" in our HardCore server)
- [ ] Replace the commandblocks at the spawn area with configured Warps teleporters

This mod is perfect for replace the commandblock wich are very ugly and very buggy (when a player lag and punch the button of the command block more than 1 time, the command block teleport more than 1 nearest player...)

**Comment by ObaniGemini** [comment]
It would be good to add secret warps on the map that teleports to some sort of big dungeon.

**Comment by LeMagnesium** [comment]
@ObaniGemini, we will need explorers for this, maybe @Ombridride would do it.

**Comment by ObaniGemini** [comment]
@LeMagnesium : an HardCore server with RPG features needs some secret places. Legends are made for people search them :)

**Comment by LeMagnesium** [comment]
Yes, but you can't preview where the dungeons will be generated, you need someone to find them before.
Another good idea would be to generate a labyrinth underground or in the sky with `maze` and make mobs spawn in it, with a destination point at the entrance.

**Comment by Ombridride** [comment]
A mod for your idea is very difficult to do @ObaniGemini, but it's possible to me to can create some secrets areas manually :)

**Comment by ObaniGemini** [comment]
@Ombridride @LeMagnesium : I'm not talking about a random generated  dungeon, but about a dungeon built by someone of you admins, that would be in the air or into the earth :). A little bit like that map you've done with WorldEdit @LeMagnesium

**Comment by LeMagnesium** [comment]
Mazes can fit that description, if they are generated properly. Also, there should be a way to disable /home and /spawn when you're in a maze..

**Comment by ObaniGemini** [comment]
@LeMagnesium : nice, are the maze very big?

**Comment by Ombridride** [comment]
The maze can be the size we want, and it's indeed a good way to use this new mod :)

But we need two things : 
- Disable the _/home_, _/spawn_ and _/sethome_ in maze. 
- We need also maze in indestructible nodes, and we need a chest with interresting loots

(PS : as i think it, regenerate a chest every 24hours without the chunk loaded still not possible ?)
(PS2 : @LeMagnesium, do you added the node wich "load the actual chunk" below the coordinations of the chest you generate with your mod ? or do we use the Wuzzy mod for it and add the node for load chunck into it ?)

**Comment by LeMagnesium** [comment]
> We need also maze in indestructible nodes, and we need a chest with interresting loots

Unbkreakable nodes' itemstrings can be passed as arguments for `/maze` , so it's not a problem. However, generating chests will be. The labyrinth is created so that corridors have 2 blocks height, and 1 block width. You can't place chests in that. Yet, you can set some commandblock giving food around the labyrinth. Even if I added `forceload`'s anchors, no chest can be placed in these labyrinths, unless it's at the entrance of the labyrinth, in a 'start room', refreshed regulary with food.

I will soon add an inhibiting system to `spawn` and `sethome` to work with `maze`.

**Comment by gravgun** [comment]
be03e62452fcd571554f
