### ISSUE TITLE
"mt_essentials" mods

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#57]
Parts of mt_essentials usefull for us ?

- [x] clear_inventory :
- (/clearinv <playername> (optional) : clear your inventory)
- => We already have this feature in the inventory GUI

- [x] players
- (/players : list all players present on the server)
- Add an alias for also used the command _list_players_
- => do we have this feature out of the "/status" informations return ? This specified command can be useful, we need to try it (add a screenshot here ?) and maybe think about the integration of this mod

- [x] spawn
- (/spawn : return to spawn)
- (/setspawn : set the world spawnpoint)
- => We already have this feature, no need to add this mod

- [x] simple_warp 
- => We don't need this mod, we are going to implement the [Warps] mod https://github.com/Ombridride/minetest-minetestforfun-server/issues/56

Forum mods link : https://forum.minetest.net/viewtopic.php?f=9&t=11969
Github mods link : https://github.com/indriApollo/mt_essentials

(PS : if a mod is added to the server, make a specified folder for him and add a line in world.mt)

**Comment by LeMagnesium** [comment]
About cleaninv : Why not adding it, it's just a tiny command, we should just throw it in `_misc`
About list_players : The command's name is /players. Here is what it looks like :
![https://lut.im/HhWPgHMS/0CvZBGbM]()
/status is usually enough however.

**Comment by Ombridride** [comment]
Ok, let's go add clear_inventory(tiny, easy, why not) and  list_players(it's tiny, the command is clear and the view is interresting)

**Comment by LeMagnesium** [comment]
I only added `/players` as `/list_players` : /clearinv is already implemented as /clearinventory, with more options.
https://github.com/Ombridride/minetest-minetestforfun-server/commit/34b36d7f66cde24b90423515be7b93268470f433

**Comment by Ombridride** [comment]
@LeMagnesium, if you over a ticket, you can close it without problem :)
