### ISSUE TITLE
[Mapper] How to generate colors.txt

### ISSUE THREAD

**Issue by LeMagnesium** [Ombridride/minetest-minetestforfun-server#59]
Here is a tutorial asked by @Ombridride to generate `colors.txt` file for minetest-mapper.

 * First, in the mapper repository, you will find this file : https://github.com/minetest/minetestmapper/blob/master/autogenerating-colors.txt . Open it.
 * In this file you will find three spaces. There are three steps to do :
  - Create a mod, called "dumpnodes" for example, and past the first part (except the banner) in its `init.lua` file.
  - Create a file called `avgcolor.py` , and paste the second part of this file into it (without the banner)
  - Finally, create a `.sh`file in which you will paste the third and last part of the file. Make sure `avgcolor.py` and.. maybe  `gencolors.sh` are in the same directory.
 * Launch the server with the dumpnodes mod enabled. Use `/dumpnodes`.
 * Remove the mod (it's useless now)
 * Go to your mapper's directory, containing the `.py` and `.sh` file.
 * Get the `nodes.txt` file in minetest's bin directory and put it with the two other files.
 * Launch `./gencolors.sh`. It may throw errors with texture you can't find the average color of, because they are invisibles.
 * You get a full `colors.txt` file written by `gencolors.sh`

This will be closed when the colors.txt will be generated.

**Comment by Ombridride** [comment]
I think the better way to do that is an automate task.

Because if we add new textures, our mapper will be incomplete...

Can you add the mod you speak about in the _~/mods/_ of our repository ?

The next time we merge the server, I will automate the task for the color.txt in my merge script, thereby im sure we don't loose any textures for our mapper :)

**Comment by LeMagnesium** [comment]
Done.
https://github.com/Ombridride/minetest-minetestforfun-server/commit/40c624c8327972965e9f4f11ee9fcc0c1df1f718

**Comment by Ombridride** [comment]
Need tweak for the emplacment of the _node.txt_

**Comment by Ombridride** [comment]
Finally rights problem, the script works well, i've updated the colors.txt file, i will edit my upgrade script to integrate this colors generation script

**Comment by Ombridride** [comment]
The script isn't good because of it's format, look at here for understand what im talking about : http://zerobin.qbuissondebon.info/?1e6a94914d6670f2#6V3PXafRqPbBRoO4pOxkNe9LPPuGTPNtlsowN8X8a3g=

**Comment by LeMagnesium** [comment]
[Here is the colors.txt I get with the same process](http://zerobin.qbuissondebon.info/?b383129de1417a0b#AZ9bZNOhvOkctzSXjHNkDWq+UBF26e4EeU9CDDo2GjQ=). So clearly, I explained it wrong. We should do it step by step together when we have time to.

**Comment by Ombridride** [comment]
@LeMagnesium @gravgun 
Assigned to @gravgun because he offered his contribution to this task and will create a script (in Lua or a system language) to create automatically the __colors.txt__ and place it at the right place (in our world directory)

**Comment by gravgun** [comment]
830a7924c98b106ebfbf383b231ad507c1829aaa \o/
