### ISSUE TITLE
Boat table

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#61]
The boat mod will be added soon to the server, so we need to do some things :

- [x] Tweak the rotate speed of the Expert boat
- [x] A boat board needs to be added to the spreadsheet 
- [x] And added to the website section "mods" (screenshot of the spreadsheet)

(players can't know what is the better boat without this...)

**Comment by ObaniGemini** [comment]
Players can know what is the best because of the cost of boats (as if I don't like this state of mind)

**Comment by Ombridride** [comment]
Yes, like you i have the same state of mind about the "more precious it is, the better it is" for boats, i don't like very much this notion... (it needs to be more realistic)
We can tweak boat ressources later, and just add a dye for the color (because it's more simple to keep the actual textures)

(My point of view for boats)
The ressources can be like that : 
1 - wood (just that)
2 - hard wood
3 - hard wood + steel(metalic parts) + tree trunk of ..... (mast) + cotton ?(sails)
4 - hard wood + mithril(metalic parts) + nether tree trunk (mast) + cotton ?(sails)

We can also used the boat skin of "Lord Of The Test" for the board 3 and 4 (because of the mast/sail)

**Comment by ObaniGemini** [comment]
Also,  when I'll come back into the server, maybe I'll can make some help rooms near of the spawn.

**Comment by Ombridride** [comment]
What is the boat speed+rotation order please ?

After test, it's strange, i think the _Moon boat_ is the more faster Oo

(Maybe our modifications need tweaks...)

**Comment by ObaniGemini** [comment]
Ask to @LeMagnesium , he remade all the stats of the boats, after have cleaning the code

**Comment by LeMagnesium** [comment]
About the levels of boats (from slower to faster) :
 1. Simple wood boat (`boat`)
 2. Race boat (`race`)
 3. Expert race boat (`expert_race`)
 4. Water boat (`water`)
 5. Moon boat (`moon`)

**Comment by ObaniGemini** [comment]
@LeMagnesium expert race is shit. It's not a really fast boat and it is awful to turn with it.

**Comment by Ombridride** [comment]
Yes @ObaniGemini, we need to give the expert race boat a better roration level

**Comment by LeMagnesium** [comment]
There. Expert boats rotate slower, so that they are easier to control.
https://github.com/Ombridride/minetest-minetestforfun-server/commit/5c6b86946cace16701821c8a3e4b90a3162fa65a
I will add a section to the calculus sheet soon.

**Comment by Ombridride** [comment]
Added to the website http://minetestforfun.qbuissondebon.info/index.php/le-jeu/liste-des-mod
(and the spreadsheet is up to date)

So i close the issue, if somebody have the time and want new boat wth better craft/textures, i invite you to create an another issue for the boat recast :)
