### ISSUE TITLE
whoison better alias

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#62]
Add the _/played_ alias to the mod whoison

Better than "/timeonline".
The more commands alises we have, the better it is for players use :)

**Comment by LeMagnesium** [comment]
I will introduce it with my rewriting of `whoison`.

**Comment by LeMagnesium** [comment]
A little thing I discovered : it seems that `/timeonline` is buggy, it didn't save anything on my local server.

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/621cbdf04b128e3bbf4a7fbd2773e8418eb0dab8

**Comment by Ombridride** [comment]
This is not a good tweak
We need /timeonline + /played, not only /played

**Comment by LeMagnesium** [comment]
How the h*ll do we need two names for one command?! You don't need 6 itemstrings per nodes nor 8 version or a texture, that's nonsense! It will surely **confuse** players, and **increase the risks of a command name collision from another mod**, excluding the fact that it might be a pain to maintain!

**Comment by Ombridride** [comment]
We talked about that on IRC.
Issue closed, the alias for this mod is commited
