### ISSUE TITLE
Mana no more regen

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#63]
After the merge of yesterday, the mana no more regenerate... :/

**Comment by LeMagnesium** [comment]
This is normal, solarmana overrides mana's regen time. The only way to regen is to be in the sunlight, or on one of the nodes registered in solarmana's table. This is the normal behavior.

**Comment by ObaniGemini** [comment]
@LeMagnesium are you sure? I'll ask b91b if he was in a mine or not so...

**Comment by LeMagnesium** [comment]
If he was in a mine, standing on ores will regenerate his mana.

**Comment by ObaniGemini** [comment]
Yes, I tried and it works. Issue can be closed

**Comment by Ombridride** [comment]
So we need to explain it in our news.txt file

**Comment by Ombridride** [comment]
The mana regeneration seems to be to low on sun light

**Comment by LeMagnesium** [comment]
if sun_light >= 15 then

Indeed. Light can't be higher than 15, which is rare. Dicreased to 14.
https://github.com/Ombridride/minetest-minetestforfun-server/commit/333a1fa6e48bad8aea5ca9c9594b39f4c583a890

**Comment by Ombridride** [comment]
Need a test after the next merge before we closed the issue

**Comment by ObaniGemini** [comment]
solarmana works, but it's still very slow, as day time is just for 10 minutes and light 14 is only active when player are in a plain with not any shadows (seems like light dicreases when player is approaching frome a block)

**Comment by Ombridride** [comment]
Ok, thank you for your return of test @ObaniGemini 

So, you want blocks they regen your mana ? They already exists ;) (see the spreadsheet if you want blocks/values informations)

Indeed, actually the mana restaured with sunis very low/slow, we need either increase the sun regeneration or deacrease the sun needed by solarmana.

I think the right solution is the first i sayed :)

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/23a6bc4b8def6b6fb333dc555a67043716512ebb ?

**Comment by Ombridride** [comment]
I merged this night, we need to test it after that, with a regeneration rate of 3, i think it will be better ;)

**Comment by Ombridride** [comment]
Solved and tested
