### ISSUE TITLE
Check commands..

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#64]
Check the wooldown time between the commands /home and /sethome, maybe the wooldown time between this commands have changed with our strang merge... ?

**Comment by LeMagnesium** [comment]
1. How would it? We didn't affect `sethome` in our merge.
 2. The last modification made to `sethome` dates back 2 months ago.

**Comment by LeMagnesium** [comment]
Nothing was changed. When you have doubts about these things, looks at the code itself.
