### ISSUE TITLE
Lavashroom biome spawn

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#66]
We need to tweak the "Lavashroom" spawn, it will be only under -200 !
(this mushroom is just biome, no craft recipe with it and no another uses, just here for make the surface biome heavier...)

**Comment by Ombridride** [comment]
Now four times more rarer : https://github.com/Ombridride/minetest-minetestforfun-server/commit/1cfa58aea6c742802de2cba5c74aebfc4dbbdfcb
(But don't found a specified setting or line for make it spawn under -200)

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/9086fbf24016d46d037a903452858665b2ae259b
Solved.

**Comment by Ombridride** [comment]
Reopen the issue because of the @HybridDog comment => https://github.com/Ombridride/minetest-minetestforfun-server/commit/9086fbf24016d46d037a903452858665b2ae259b

**Comment by HybridDog** [comment]
When you write spawn, do you mean the abm or mapgen?

**Comment by Ombridride** [comment]
We need the both. However ABM mainly

**Comment by HybridDog** [comment]
>However ABM mainly

But if l disable lavashroom spawning near lava above -200 you would need to go down for mushroom farming. Lavashrooms only spawn near lava if there's no sunlight and a cracky node under it.

**Comment by LeMagnesium** [comment]
@Ombridride wanted to move them in order to make the surface biome less heavy even though they don't appear much. I will remove my modification, and I don't think that this issue's goal should be achieved, lavashrooms aren't troublesome.

**Comment by HybridDog** [comment]
>Ombridride wanted to move them in order to make the surface biome less heavy

you would only need to change the 1/4000 chance
https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/mods/riesenpilz/mapgen.lua#L247

**Comment by LeMagnesium** [comment]
Ombridride changed the global chance for mapgen, but not especially this one. Thanks for the tip.

**Comment by Ombridride** [comment]
@Gael-de-Sailly @gravgun @crabman77 
With the new mapgen, we haven't anymore riesenpilz from the [riesenpilz] mod, it's not a bad thing because the generation of this mushrooms was just esthetic (no craft linked so useless for players, just eye candies)
I can also add we haven't have anymore the mushrooms from the [plantlife_modpack/mushroom] mod (https://github.com/Ombridride/minetest-minetestforfun-server/tree/master/mods/plantlife_modpack/mushroom) BUT we still have the *mushroom seeds* items when we dig dirts, so players can create a mushroom garder if they want to craft potions from the mushroom mod

So, after this explanations, i closed this issue because we don't need it anymore ! :)
