### ISSUE TITLE
Screwdriver bug

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#67]
The mithril screwdriver doesn't work since the last update of the screwdriver function add...

**Comment by Ombridride** [comment]
@LeMagnesium introduce this issue in his last update of screwdriver, i assigned the issue to him

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/b291b1587d39206458809a324817595a4706f4ca
Fixed.
