### ISSUE TITLE
How can we communicate while inchra.net  is down? 

### ISSUE THREAD

**Issue by ObaniGemini** [Ombridride/minetest-minetestforfun-server#68]

**Comment by LeMagnesium** [comment]
Easy : use their IP addresses, or digitalaudioconcepts.com:6667 . Otherwise... I have no idea.

**Comment by Gael-de-Sailly** [comment]
Use Konversation, with address 176.9.29.178.

**Comment by ObaniGemini** [comment]
Ok thank you guys

**Comment by Ombridride** [comment]
The bot is now linked again with our IRC channel on _Inchra.net_
If you want to connect on the IRC server, you need to use the IP addresse _176.9.29.178_ or _67.241.151.78_ for SSL connection
