### ISSUE TITLE
Problem with glasses

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#69]
# Texture problem
The mod *framedglass* has a problem with it's texture, if you don't have activated *connected_glass* in your minetest graphical configuration (or minetest.conf), you see ugly grey nodes wich replaced the original texture...

### Without *connected_glass* 
![Image with problem](http://i.imgur.com/FE8PMdf.png)
### With *connected_glass* 
![Image with problem](https://imgur.com/ikaVaJQ.png)

The problem isn't here with another mod like the default glasses or with an another mod like *stained_glass* mod

# Connected option missing
The "clean_glass" doesn't have the connected option, we need to add it !

**Comment by crabman77** [comment]
Fixed https://github.com/Ombridride/minetest-minetestforfun-server/commit/5c008ce6f694a3ab9743c1f3e9c97e82384848b3
