### ISSUE TITLE
Event node with music loop

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#72]
We need to create a node with a music loop for events. (like the node from mesecons, but with a music more longer, maybe 20~30sec)

The music can be find here : https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/other_things/unused_sounds/event.ogg (Obani create it for us)

**Comment by LeMagnesium** [comment]
What if I tweak this?
https://forum.minetest.net/viewtopic.php?id=5913

**Comment by Ombridride** [comment]
Ow ! Good idea, like that we can create CD for different music :)

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/29578792a0fb84f3fd2a7f7df5ec6d813e64ca8c

**Comment by Ombridride** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/e4bbe52feb8391f00053bbdcb5b1ab8a9473d6e1

**Comment by Ombridride** [comment]
The initial mod was updated recently: https://forum.minetest.net/viewtopic.php?f=9&t=12474&view=unread#unread
Need to merge the new code to our jukebox mod

**Comment by LeMagnesium** [comment]
This redo uses a complete different organization for its code... it will be painful to implement.

**Comment by ObaniGemini** [comment]
![croche](https://cloud.githubusercontent.com/assets/11649956/8068575/e9b823aa-0ef4-11e5-8dd7-ebf24eb381b5.png)

**Comment by Ombridride** [comment]
For @ObaniGemini, i answer to you for your IRC questions :  
Je regarde ta musique
Elle est bien cette musique, mais il ne faut pas oublier que la durée doit etre entre 15 et 30sec et répétable sans brusquement
mettre un marqueur de lancement du son dans les logs importe peu

**Comment by Ombridride** [comment]
Il y a assez de musique sur ce mod, et il est maintenant totalement fonctionnel, je ferme.

**Comment by ObaniGemini** [comment]
Il ne faut pas que j'en remplec certaines?

**Comment by Ombridride** [comment]
Pas de soucis si tu veux le faire, mais je ferme ce ticket de création. 

Si tu veux les musiques à ré-ajouter, il te faut te rendre ici https://github.com/Ombridride/minetest-minetestforfun-server/issues/46 (d'ailleurs, ce ticket n'a pas été compléter, si tu pouvais le faire s'il te plait :))
