### ISSUE TITLE
Better Mapgen

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#74]
We planed to change the mapgen of the server, we need to test it in a local dev server, but it will be interresting for deleting highlandpools (too bugged), and with this mapgen we are going to have a very interresting mountains/rivers/etc... generation.

#### Comptability issue
It works with our actual core mapgen (v6) and it's written in Lua. (it's a mod so it overwrited the actual mapgen)

#### Link(s)
https://forum.minetest.net/viewtopic.php?f=11&t=8609&hilit=watershed

#### Screenshot(s)
![mapgen's volcan](http://i.imgur.com/8I9ZAP0.png)
![mapgen's floating island](http://i.imgur.com/uXgmmO9.png)

#### Internal code changes
- [x] Increase the floating islands rate
- [x] Reduce the biome size
- [ ] Tweak the caves generation

#### Nodes wich needs to be converted
- [ ] Node1
- [ ] Node2
- [ ] Node3
- [ ] Node4
- [ ] Node5
- [ ] Node6
- [ ] Node7
- [ ] Node8
- [ ] Node9
- [ ] etc...

#### Temperature unification
- [ ] Biome1
- [ ] Biome2
- [ ] Biome3
- [ ] Biome4
- [ ] Biome5
- [ ] Biome6

#### Humidity unification
- [ ] Biome1
- [ ] Biome2
- [ ] Biome3
- [ ] Biome4
- [ ] Biome5
- [ ] Biome6

#### Other information(s)
If possible, don't tweak another mods

**Comment by Ombridride** [comment]
Question here for @paramat https://forum.minetest.net/viewtopic.php?f=11&t=8609&p=182774#p182774

**Comment by Gael-de-Sailly** [comment]
I've started working on it :

https://github.com/Gael-de-Sailly/minetest-minetestforfun-server/tree/watershed

**Comment by Ombridride** [comment]
Impressive, keep up the good work !

**Comment by Gael-de-Sailly** [comment]
I've added the caves from Valleys Mapgen.
![Caves in VMG](https://camo.githubusercontent.com/813d1601db14533d8246625b256ed05b950e3b1a/687474703a2f2f692e696d6775722e636f6d2f674f4f385064682e706e67)
Should I keep the fissures that are in Watershed ?

**Comment by Ombridride** [comment]
great work with caves !
For the "fissures", yes keep it :)

**Comment by Gael-de-Sailly** [comment]
f3da59b
