### ISSUE TITLE
New Hud Bars

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#76]
This Hud Bars are better than what we actualy use, in many points :
- Progress Bars more Accurate
- No more hunger bar bug (see 20 point instead of 30)
- More "RPG-like"
- We read it more easily
- Better for big amount of mana (100 to 300 for example)
- etc...

Many mods are parts of a complete hud so, maybe we need to do a modpack with it ?

- [X] hudbars (include hud bars for health and breath, also include the API)
https://forum.minetest.net/viewtopic.php?f=11&t=11153&hilit=armor#p169488
![Wuzzy Hud Bars - health and breath](https://forum.minetest.net/download/file.php?id=1926)

- [x] mana (include hud bars for mana) => We need to update this mod first and increase the refresh counter (1 or 2 seconds between refresh)
https://forum.minetest.net/viewtopic.php?f=9&t=11154#p169490
![Wuzzy Hud Bars - mana](https://forum.minetest.net/download/file.php?id=1929)

- [X] sprint (include hud bars for sprint)
https://forum.minetest.net/viewtopic.php?f=11&t=9650#p146781
![Wuzzy Hud Bars - sprint](https://forum.minetest.net/download/file.php?mode=view&id=2004)

- [X] hudhunger (include hud bars for hunger)
https://forum.minetest.net/viewtopic.php?f=9&t=11336#p171140
![Wuzzy Hud Bars - hunger](https://forum.minetest.net/download/file.php?mode=view&id=2150)

- [X] hbarmor (include hud for armor)
https://forum.minetest.net/viewtopic.php?f=9&t=11337#p171141
![Wuzzy Hud Bars - armor](https://forum.minetest.net/download/file.php?mode=view&id=2119)

We need to fix our compatibility problems wich stop us the previous time we tried to merge this hud bars !

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/bd86d9d8f41121fe91f9a4dc62237765d4cdcd06

**Comment by Ombridride** [comment]
Everything seems to be ok, we need to tested it ingame now, for the next merge

**Comment by LeMagnesium** [comment]
![HUDBars](https://lut.im/U0RyATBw/8cCVrf4M)

We will just have to put them a little bit up and it will be fine.

**Comment by Ombridride** [comment]
Yes a little bit up and maybe re-organize the order of hudbars like this : 
Left hud bars | Right hud bars 
------------ | -------------
Sprint | Breath
Armor | Hunger
Health | Mana

**Comment by ObaniGemini** [comment]
Or maybe

Left hud bars | Right hud bars 
------------ | -------------
Vreath | Sprint
Hunger | Armor
Health | Mana

**Comment by Ombridride** [comment]
Can you explain your choice @ObaniGemini ?

**Comment by ObaniGemini** [comment]
Left hud bars | Right hud bars 

Bars that tells you you're alive | Bars showing helping things

**Comment by mgl512** [comment]
I agree with Obani: all the life bars on the same side (= breath, health, hunger). Sprint is the next most important one, it would be nice to have it at the top or bottom of the other side.

**Comment by LeMagnesium** [comment]
@Ombridride , @ObaniGemini , @mgl512 , because you think you can modify in their declaration on in `hudbars`' code the positions of these bars? Well, too bad, you can't.
See this little thing : [API](https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/mods/hudbars/API.md)

Appart from breath and health bar which are hardcoded, **you cannot change the position of a bar, it's managed by hudbars itself, which adapts the bars when they are registered to fit in a size-defined area** (and even if you changed healt and breath, the other ones could be misplaced). We cannot move the bars, but when can enlarge and move the area where they are put.

**Comment by crabman77** [comment]
hudbars are now customizable
 https://github.com/Ombridride/minetest-minetestforfun-server/commit/af4ff618bb9e50cef1d4300cbb36f9ce4582e20f

![hudbars](https://cloud.githubusercontent.com/assets/7189389/8252695/69436c7a-1688-11e5-9b0b-7fe4945e7417.png)

**Comment by Ombridride** [comment]
@crabman77 Good job !

So we keep this positions ?

Left hud bars | Right hud bars 
------------ | -------------
Bars that tells you you're alive | Bars showing helping things

Left hud bars | Right hud bars 
------------ | -------------
Sprint | Breath
Hunger | Armor
Health | Mana

**Comment by LeMagnesium** [comment]
The only problem I have with this is that whenever you don't wear any armor and aren't drowning, you will only have 1 bar shown on the right, whereas there will be 3 on the left. Otherwise, no problem.

**Comment by Ataron** [comment]
I agree with @LeMagnesium. I think armor and breath need to be at the top of right and left/

**Comment by LeMagnesium** [comment]
I would propose : 

Left hud bars | Right hud bars 
------------ | -------------
Breath | Armor
Hunger | Sprint
Health | Mana

With this, every health bar is on the left, and every information bar is on the right, while all temporary bars are on top.

**Comment by Ataron** [comment]
That's Good :D

**Comment by mgl512** [comment]
Wuzzy wrote the order can be configured in minetest.conf. Is it true ?

Because I certainly don't want my HUD bars sorted like that, People who play on MFF have to survive, and you have 0.5 seconds to react or you're dead. Your eyes don't have time to zigzag the bars to sort out the useful information like sprint, health and hunger from the crap like armor and mana.

**Comment by ObaniGemini** [comment]
For each new feature, the player needs to get used to it. It's normal.

**Comment by crabman77** [comment]
screenshoot in placement proposed by @LeMagnesium .
I upped hudbars because covers by text.    "start_offset" ->  y = -100  not -70 .

Idea: change mana background color in purple ?
![hudbars_mana](https://cloud.githubusercontent.com/assets/7189389/8271658/509b1636-1823-11e5-930c-dfa17450118f.png)

**Comment by ObaniGemini** [comment]
I think we should invert armor and breath.

**Comment by crabman77** [comment]
@ObaniGemini  in this configuration, important hudbars are left, when she are empty then you dead.

**Comment by LeMagnesium** [comment]
Well, everything is done. Can we close this now?

**Comment by Ombridride** [comment]
Yes we closed, the last problems we have are in a separated issue
