### ISSUE TITLE
Tools Unification

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#78]
We need to unify the tools of the server, the https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/Tableau-valeurs-MFF.ods is here for help us for this task.

- [x] Complete the _Tableau-valeurs-MFF.ods_ with __actual__ values for _Axe_ and _Shovel_. 

Next, we need to tweak the spreadsheet values to be more balanced https://github.com/Ombridride/minetest-minetestforfun-server/commit/4ed234d60a5def487426134936009d312bb1e35d :
- [x] PickAxe balanced
- [x] Axe balanced
- [x] Shovel balanced

And after, we must add this settings to the server https://github.com/Ombridride/minetest-minetestforfun-server/commit/8970de66042993f6d5fee925b509a93d8a45bfc1 https://github.com/Ombridride/minetest-minetestforfun-server/commit/a5b3799409b04d0a181b2ace5931125f1dfda1ec https://github.com/Ombridride/minetest-minetestforfun-server/commit/ecdad27e2723a10b4ef4c4c46f2e790e7ef8c392 https://github.com/Ombridride/minetest-minetestforfun-server/commit/4020dbe4ec3bca05bd6bf8c6ffc6afabdc5debbd :
- [x] PickAxe added
- [x] Axe added
- [x] Shovel added

Finally, post the new Tools values to the "Liste des mods" section in the Website :
- [x] PickAxe posted
- [x] Axe posted
- [x] Shovel posted

**Comment by LeMagnesium** [comment]
Don't forget the commits.
https://github.com/Ombridride/minetest-minetestforfun-server/commit/4ed234d60a5def487426134936009d312bb1e35d
https://github.com/Ombridride/minetest-minetestforfun-server/commit/a5b3799409b04d0a181b2ace5931125f1dfda1ec
