### ISSUE TITLE
Buckets problem

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#80]
JAPP tolds me the water and lava can't be took by bucket !
We need to check that and fix the problem if it's really a problem...

_Original message from JAPP :  Impossible de prendre de l'eau ni de la lave. Même les seaux d'eau ne sont plus disponibles dans le craft guide lorsque l'on tape une recherche avec par ex bucket._

**Comment by LeMagnesium** [comment]
Water buckets don't appear in non-creative inventory when searching "bucket", but yes, water buckets are buggy.. I'm on it.

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/3da163893f6c44b3b77190beaa0c5450ff080351
