### ISSUE TITLE
Farming light

### ISSUE THREAD

**Issue by mgl512** [Ombridride/minetest-minetestforfun-server#82]
Elle est de nouveau à 13 au lieu de 11 (constante MIN_LIGHT dans 'init.lua' de farming), probablement à cause de la mise à jour fu mod.

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/cc7e126c7afc7fa60d85c778ec3944a948bfd3ea

**Comment by Ombridride** [comment]
The line was commented, now we will no longer do this error
