### ISSUE TITLE
farming:straw vs darkage:straw

### ISSUE THREAD

**Issue by mgl512** [Ombridride/minetest-minetestforfun-server#83]
La paille de darkage a été supprimée au profit de celle de farming. La paille de darkage, darkage:straw, était enregistrée auprès de stairsplus, la scie de Calinou, et offrait bien plus de possibilités créatives que le bloc seul de farming, qui ne l'est pas. C'est la recette de paille de farming qu'il aurait fallu supprimer ou modifier, à mon avis, pour qu'elle produise un bloc darkage:straw plutot que farming:straw si darkage fait partie des mods (optionels).

**Comment by crabman77** [comment]
Fixed https://github.com/Ombridride/minetest-minetestforfun-server/commit/cfdbe7146675fa06d79a9882da2af6e9892a2bf6

**Comment by LeMagnesium** [comment]
You should have created an alias and removed the craft recipe from farming, but not modified darkage itself..
