### ISSUE TITLE
Too much monsters !

### ISSUE THREAD

**Issue by ObaniGemini** [Ombridride/minetest-minetestforfun-server#84]
There are too much monsters ! Even at day-time !
The spiders spawn too much : I many times had three spiders in 30 voxels of distance.

CGT ASKINGS : 
- There are two much spawning monsters on the server !
- Swords don't have enough damage points ! It's boring to take 15 seconds to kill a monster !

**Comment by Ataron** [comment]
Right like all the sand monsters, I go to my building with Yvan and we need to kill 4 of them more a minotaur --'

**Comment by paly2** [comment]
This is right, there are lot of spiders... Jungles are already very dangerous with tree monsters...

**Comment by ObaniGemini** [comment]
Also, all those things increases all the permanents ragequits

**Comment by YvanYr** [comment]
Right! +1

**Comment by mgl512** [comment]
2 raisons pour lesquelles les nouveaux joueurs ne restent pas, quand ils veulent bien les dire: lag au spawn et monde trop hostile. On voit Cyberpangolin se faire tuer extrêmement facilement en full fer contre un dirtmonster dans l'une de ses vidéos. Par une araignée dans une autre. les nouveaux joueurs se font tuer plein de fois en quelques minutes par des sandmonsters et des araignées, deux des monstres les plus faibles et pourtant désavantagés par l'eau au spawn. Ces monstres sont aussi des bouchers pour les NPC. 
 
Je ne pense pas qu'on pourrait faire, aujourd'hui, une visite du serveur pour un nouveau joueur comme on le faisait avant, parce qu'on a une espérance de vie trop courte quand on fait du tourisme maintenant. 

-- Le_Docteur

**Comment by ObaniGemini** [comment]
@mgl512 : Je pense que c'est un bon résumé du principal problème du serveur. De plus, comme tu l'as dit, les lags font parfois apparaitre les monstres à un bloc du joueur, et vu leurs DPS et leur vitesse de déplacements, il est très difficile de les vaincre, sans compter les obstacles qui peuvent se trouver sur la route (fossés, acide,...). Bien que ces monstres soient bénéfiques au côtés hardcore du serveur, l'instabilité de leur comportement ainsi que de celui du serveur influe surl'expérience que le joueur a : il est toujours plus frustrant de se faire tuer par un bug que par sa propre faute.

**Comment by LeMagnesium** [comment]
Hardcore has limits.
Old players, with enough items to fight monsters shouldn't be beaten by the same monsters as new players. New plays should also be able to kill some of them : **at the moment, I don't even think there is a monster you can beat with a bare hand in less than 3 minutes**.
Making simple monsters spawn very often is good, but everyone should then be able to fight them and maybe win, whereas mighty monsters should spawn less often. Maybe dicrease a bit the power of spiders and sandmonsters?

Also, animal_modpack provided some blocks designed to capture monsters (zombies in this case). Why wouldn't we implement nodes like these? Two kind of them should exist : one for admin, uncraftable, with a large range (to protect areas around public buildings for new players) and another one, with a smaller action radius, craftable.
What do you think of this?

**Comment by ObaniGemini** [comment]
Sand monsters are easy to kill as they spawn on sand, and die in water. But there are more spiders than sand monsters, and they are harder to kill. Also, I think some of you should not understand the problem because you play rarely on the server. @LeMagnesium , @Ombridride : try to play 2 hours as a beginner that tries to make his own house, and tell us what do you think about it :)

**Comment by LeMagnesium** [comment]
> try to play 2 hours as a beginner that tries to make his own house

This is impossible do to without dying at least 10 times. With no stuff I'm killed half of the times when I go from the old spawn to my house.

**Comment by Ombridride** [comment]
Hi everybody, 
First, thank you for the many interresting activities on this thread !

For the spiders : https://github.com/Ombridride/minetest-minetestforfun-server/commit/c63396ef38840f99d0a2055b7a018acadfd4ce45
=> new spawn rate 10 000 (before 9000)
For the sandmonster, i've already tweaked his spawn rate (before 8000, after 15000), but i haven't really see a difference between 8000 and 15000... I've also tweaked the spawn rate to erase the spawn on beach sand (with is the nodes near the spawn)

I think we need a huge /clearobjects => executed now, answer me here is something was changed ;)

**Comment by ObaniGemini** [comment]
The problem isn't really the amount of monsters, but our capacity to kill them. Actually they're really too strong and buggy for we can kill them easily without blocking them into a cliff or behind a wall.

**Comment by Ombridride** [comment]
Ok,
what do you think about that tweaks ? 
https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/mods/mobs/spider.lua
https://github.com/Ombridride/minetest-minetestforfun-server/commit/fc11c92a9f343ca77f7ad23bd891dc678e0aecae

**Comment by LeMagnesium** [comment]
Well, at least, now you can run away more simply, but it won't help much for what @ObaniGemini talks about I suppose.

**Comment by Ombridride** [comment]
The problem is solved
