### ISSUE TITLE
Beds problem

### ISSUE THREAD

**Issue by ObaniGemini** [Ombridride/minetest-minetestforfun-server#85]
It seems like simple beds don't work to set the spawn, but fancy beds work.

**Comment by mgl512** [comment]
Tous mes tentatives de faire passer la nuit dans un lit simple ont échoué a creer un spawn alors que les rares fois où je l'ai fait dans un lit "fancy" ont réussi systématiquement. 

Les deux lits utilisent la même fonction d'enregistrment (qui leur colle "inflammable" dans les groupes a

**Comment by mgl512** [comment]
Est-ce que ça peut être parce qu'on entrerait en collision contre un lit simple si la création du spawn se faisait, et qu'elle est silencieusement refusée à cause de ça ?

**Comment by LeMagnesium** [comment]
I will soon replace Blockmen's old version by the fork he put into Minetest Game for merge reasons, and also because it is up-to-date, whereas our version isn't.

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/349e44eedc1ba0c7df0fe821d79e7212cb798fbd
Keep this open until I see if old nodes are still supported.

**Comment by Ombridride** [comment]
After the next merge (Github -> MFF server), we need to check this point seriously

**Comment by mgl512** [comment]
Comme suggéré par Crabman, j'ai dormi dans un lit simple sur le serveur sans cliquer sur le bouton "Skip night" et le spawn a bien été créé. Tous mes autres tests ont été faits en cliquant sur ce bouton. Peut-être que les rares fois où ca a marché j'ai été trop lent pour cliquer et que c'était un hasard que ça tombe sur un lit "fancy".

**Comment by LeMagnesium** [comment]
@mgl512 , Minetest Game's version of `beds` has already fixed this issue, and many mores. Since it's the only maintained version of beds (and because it is included in Minetest Game) we decided to replace our old version by this one, which includes new features.
I just checked, and beds aren't unknown nodes, they are just half a bed. So if you see one, dig it, and place it back.
Closed.

**Comment by Ombridride** [comment]
I will reset the __bed spawn point__ (= delete the __bed spawn point__ file from _/world/minetestforfun/*_) when we merge this issue to start of again with a clean bed mod
