### ISSUE TITLE
Mods Updates

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#87]
- [x] MAJ colormachine : https://forum.minetest.net/viewtopic.php?f=11&t=6670&view=unread#p179411 (grosse réécriture)
- [X] MAJ de mana : https://forum.minetest.net/viewtopic.php?f=11&t=11154&view=unread#p179622 (pas mal de choses, principalement le taux de régénération modifiable à la volée plus facilement, qu'il faudrait adapter avec nos valeurs actuelles)
- [x] MAJ bedrock ou nouveau bedrock ? : https://forum.minetest.net/viewtopic.php?f=11&t=9231&view=unread#p179064 (bedrock de Wuzzy ici : https://forum.minetest.net/viewtopic.php?f=9&t=11271&view=unread#p170611)
- [x] MAJ de snow (avec dernière version dispo uniquement sur github, le sled a été fix) : https://github.com/Splizard/minetest-mod-snow
- [X] MAJ de Moreblocks : amélioration de rapidité du code

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/6ad7ddbeec514f805db8332df9f401f9e6725ef8

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/4ad0939fe6dd6c65dc9a7ed0b54aa8bbbc40d5b5

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/e4ef41d7af5e33fc5d06ad5fb3fb5067b29f3a8e

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/b8e61fd763aa2360c4d9af967bccf4d3a3575ac0

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/4bc80ddba1ae82aac60952b5f53c459bfe211f9b

**Comment by Ombridride** [comment]
Removes meshe slopes from moreblocks mod (very ugly :/) ?

**Comment by LeMagnesium** [comment]
Bedrock is Wuzzy's one.
I will remove slopes.

**Comment by LeMagnesium** [comment]
See https://github.com/Ombridride/minetest-minetestforfun-server/commit/c38b9b66acb3566c786585b54ef8b920600ba768 .
I kept slopes file to make merges easier, but commented its `dofile`.

**Comment by Ombridride** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/0121443f89e27793e8909e390e480d93bca3a5a3

Everything is ok, i closed the issue

**Comment by mgl512** [comment]
I've been using slopes for months on MFF. They always existed. It's just that they weren't in the saw menu. You can't just remove them now.

**Comment by LeMagnesium** [comment]
I agree with @mgl512 , we can't just remove a node because it isn't cubic-like, or because it is 'ugly'.

**Comment by Ombridride** [comment]
I didn't knwo that point, so we let this feature https://github.com/Ombridride/minetest-minetestforfun-server/commit/9b7cb336f7721c0b32f2188c2b0804edbf1253b4

**Comment by LeMagnesium** [comment]
And https://github.com/Ombridride/minetest-minetestforfun-server/commit/67ef5454ed9db553f870cc5c60c50d1a4ad5ec1c.

**Comment by mgl512** [comment]
See my house at (1900, _, 400). It was built a few months ago in the purpose of experimenting slopes. It's full of them: roof, walls... It's not ugly (I hope). Its new extension looks a bit weird because of the different slope angles I tried on its roof, but it's not that bad.

**Comment by Ombridride** [comment]
Ok @mgl512 , since i played not very much right now, i haven't see your house :)

Anyway, the slopes are re-added, I closed the issue.
