### ISSUE TITLE
Flowers problem

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#88]
### Testimony
Yvan has seen many __unknow nodes__ near -864, 2, -196 !
The __unknow nodes__ are created by **flowers:lily_pad**

**Comment by LeMagnesium** [comment]
Oops. My fault, when modifying flowers. https://github.com/Ombridride/minetest-minetestforfun-server/blob/060e03b003baeba80990b939a5d6ec3dd33948b7/minetestforfun_game/mods/flowers/init.lua
Fixed.
https://github.com/Ombridride/minetest-minetestforfun-server/commit/97dafe87cebd27daad93569d1d8cfb6272e10f2d

**Comment by Ombridride** [comment]
I think so, no problem, good fix/job :)
