### ISSUE TITLE
Show locked chest formspec to others or not ?

### ISSUE THREAD

**Issue by mgl512** [Ombridride/minetest-minetestforfun-server#90]
I'm looking at the chests and noticed that minetest_game decided to hide the formspec of a locked chest to anyone who's not the owner. On MFF, after the merge, the code to hide it blended with the code to show it, and doesn't work (Edit: I pushed the commit 3f9ffdc, wich more or less shows it). Hiding the formspec of locked chests would only work on newly built ones. 

Someone has to decide if MFF will comply to the policy of minetest_game on the formspec of locked chests or not.

**Comment by LeMagnesium** [comment]
Formspecs are hidden to anyone how isn't the owner. Period. We will keep this.
Minetest Game's function to get formspec was overriding the builtin's work to hide the formspec. With your commit, anyone will be able to see it, so I will probably revert this soon.

**Comment by mgl512** [comment]
It's not my commit, it comes from your merge with minetest_game. My commit only fixes the name of the formspec function. 

You'll have to remove the call to the formspec function on the "on_construct" event, which doesn't come from me and uncomment the "on_right_click" thing, which comes from me and is currently useless because of the "on_construct" code. 

Only the newly built locked chests will have a hidden formspec I think. All the existing ones since the beginning of MFF should keep their formspec visible by others.

**Comment by Ombridride** [comment]
Good point @mgl512, I think we should keep the **MT_game** feature for locked chests

**Comment by mgl512** [comment]
So confusing... Minetest_game now tries to hide the formspec to others. It's a recent change. So you mean that newly built locked chests should comply to this or not ?  To comply, the code on the event "on_construct" must be fixed because it shows the formspec whatever you do on the "on_right_click" event. 

Either we keep the new locked chest with a visible formspec like the ones which have been placed in the world of MFF since its beginning or we change the code (especially on_construct) to make the newly built locked chests comply to the new minetest_game policy of hiding the formspec to others.

Whatever you do, don't revert my commit, it fixes a bug which calls a nil function on the "on_right_click" event.

**Comment by LeMagnesium** [comment]
> So confusing... Minetest_game now tries to hide the formspec to others. It's a recent change.

No, it isn't. You can't see inside other's chest since 0.4.5 (as far as I remember). It's just that they used a different way to do this.
I will carefully put back the `on_right_click` code and see where is the error from.

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/251661fb5263d4f7a5c82028c3895af5f4d2d4c3
