### ISSUE TITLE
Sunflowers problem

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#93]
The sunflowers plants from the _plantlife modpack_ is going to be a seriously (big) problem.
The spawn doesn't seems to be limited per chunck, so the sunflowers grows, grows, and grows again... 
I can see right now chunck (100x100 areas) completely full of Sunflowers !

This problem __needs to be fixed as soon as possible__ !

We can now found areas like this... 
![Sunflowers spawn problem](http://i.imgur.com/2tNg6xe.jpg)

(EDIT : maybe @VanessaE can help us ?)

**Comment by ObaniGemini** [comment]
Aouch. Maybe should you remove all those after having implemented a fix number per area

**Comment by mgl512** [comment]
Are you sure they expanded recently in this area ?  I used to constantly destroy tens of them near my house weeks ago but their expansion seems to have stopped now.

**Comment by Ombridride** [comment]
I think their expansion is with a condition "if any other sunflowers are near", the initial spawn isn't the reason of this impressive invasion :/

**Comment by VanessaE** [comment]
I've long since fixed this in git, and don't see the out-of-control spreading on my local worlds anymore.

Can someone else confirm please?

**Comment by Ombridride** [comment]
The MFF server runs the latest version of plantlife_modpack, i can see your fix in commits section on your repository. 
But even with this fix, the amazing spawn is always here, maybe strange ?

**Comment by LeMagnesium** [comment]
This section was probably generated long ago.
You should try to regenerate. (it reminds me I have to disable riesenpilz's biome which has appeared, and I don't know why...)

**Comment by mgl512** [comment]
I can confirm what Vanessa said: I planted 10 sunflowers in a plain on my working copy of the MFF repository, and let the game roll for 30 minutes in the area. Only 7 additional sunflowers grew. It's far from being out of control. For me it was fixed some time ago.

**Comment by VanessaE** [comment]
Thanks, mgl512; sounds like it could still use a small tweak but it's good enough for now.

Besides, they won't spread outside of the usual fertile-land perlin map anyway.

**Comment by LeMagnesium** [comment]
I generated some sunflowers on a test map, just as @mgl512 did, and after some time spent playing around them, and a long idle of my avatar, there weren't much of them. These areas have been generated just after plantlife introduced sunflowers. Since, their mapgen's parameters were modified.
Just regenerate the lands to wipe the sunflowers off.

**Comment by Ombridride** [comment]
Ok, i moved the issue tag to _Minetest 0.4.13-Release_ because i can't do a /deleteblocks without an upadte of the minetest_core game on the server

**Comment by Ombridride** [comment]
Resolved because we changed our mapgen
