### ISSUE TITLE
Bugs dernier merge serveur

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#94]
## Bugs découverts suite au dernier Merge du serveur

- [X] MAJ de "mobs" (ajout des dogs en compagnon, s'obtient en nourrissant un loup avec 4 "mobs:meat_raw" et bugfix de la nourriture du NPC et dog, attention le dog est plus faible que le NPC en tant que compagnon, debug de la restauration de vie des compagnons)
     - [x] Crash lorsque l'on veut tamed un wolf (http://zerobin.qbuissondebon.info/?0a7f6c2ef8a5e6c1#WwmB6OewMgzPFZ+4/4k2kBfdu6JNBeAXuA2JtzvFKbg=) => https://github.com/Ombridride/minetest-minetestforfun-server/commit/822e54fa0cb4c060b0a55a7f1176b24b0b0d04e5
     - [X] On ne peut plus tamed les NPCs avec 4 diamants ? le bread est sensée le soigner rien d'autre => https://github.com/Ombridride/minetest-minetestforfun-server/commit/94417bcafc1454cad27dda535a69b7d0a5eb8942
     - [x] Ajuster le spawn des Yétis pour le nouveau biome neigeux => https://github.com/Ombridride/minetest-minetestforfun-server/commit/0eb94d50592cbbe24c7338414b75308d33a0a2f3
     - [x] Le taux de spawn des Minotaur doit être baissé => https://github.com/Ombridride/minetest-minetestforfun-server/commit/f3ee47a526767a74041c817bd28b16af5d0023f1
     - [x] Le taux de spawn des Sand Monster doit être baissé => https://github.com/Ombridride/minetest-minetestforfun-server/commit/60cb71e385c2359d3ac660e92ca68faf24623559
     - [x] Les creepers ne tue pas les joueurs meme s'ils sont tout nu, ce n'est pas le fonctionnement souhaiter à la base

- [x] Ajout du mod "hudbars", "hbhunger" et "hbarmor" (nouvelles barres pour une meilleure visualisation des statistiques de votre personnage)
     - [x] la faim descend de façon linéaire, si l'on mine elle ne descend pas plus rapidement, pareil si l'on marche... la fonction exhaust de l'ancien hud n'est plus là
     - [x] Remettre l'ancienne texture "overwrite" de viseur => https://github.com/Ombridride/minetest-minetestforfun-server/commit/78734c70ce9b452ae221f0cb3926ef4746279f68
     - [x] Remettre l'ancienne texture "overwrite" de main/hand => https://github.com/Ombridride/minetest-minetestforfun-server/commit/78734c70ce9b452ae221f0cb3926ef4746279f68
     - [x] Remettre l'ancienne texture "overwrite" du fond de barre de raccourcis d'objet => https://github.com/Ombridride/minetest-minetestforfun-server/commit/78734c70ce9b452ae221f0cb3926ef4746279f68

- [X] MAJ de "MFF/nodes.lua" (ajout d'un son pour le gravier/gravel)
     - [X] Le son mis actuellement mis sur le _gravel_ étant déjà utilisé pour la _dirt_, il serait mieux d'utiliser le son du _maptools:gravel_ à la place (le son fait d'ailleurs bien plus gravier) => https://github.com/Ombridride/minetest-minetestforfun-server/commit/2b937048105bafdc1fb2ab8a8ceb5ec2f08f784e

- [x] MAJ de "MFF_subgame" (beaucoup d'ajouts issus des dernières nouveautés de "minetest_game", amélioration de code, ré-organisation de code, suppression de codes inutile de Carbone, nouvelles textures compressées pour la laine/wool, ajout du meuble "vessels" permettant le rangement des récipients comme les potions et bouteilles, optimisation des textures des lits/beds, bateau/boat maintenant en meshe, optimisation du code des fleurs/flowers, ajout des cherry_tree dans les zones nouvellement générés de la carte)
     - [x] Ok pour le meuble vessels, mais on ne peut mettre les *mushroom:brown_essence* et _mushroom:poison_ dedans (https://github.com/Ombridride/minetest-minetestforfun-server/commit/3beb54099bc6ad657e4572e1f4dee9c70971d237)

- [x] MAJ de "MFF/xpanes" (nouvelle texture pour les "xpanes_bar")
     - [x] Se casse à la main actuellement, pourtant fait en _steel:ingot_, lui mettre une valeur de cracky plus élevé et obligeant l'utilisation d'une pickaxe, comme pour miner du _steel:ingot_

- [x] MAJ de "MFF/bucket" (ajout de l'eau de rivière et du seau associé/bucket_river_water)
     - [x] Les rivières sont sensées être générées sur les nouvelles zones de la carte ? => Non pour l'instant. Oui si l'on upgrade le jeu en 0.4.12-dev (ou plus)

- [x] MAJ de "snow" (amélioration du code, optimisation générale, ajout de beaucoup de choses comme les fleurs dans le biome neigeux, debug des luges) => encore utile après le merge du biome neigeux de MT_game ?

- [x] MAJ de "bedrock" (remplacement du mod de Carbone par celui de Wuzzy car amélioré et surtout moins faillible)

- [x] MAJ de "jukebox" (maintenant STABLE - ajout de musique, ajout d'une texture note de musiques lorsque activé)
     - [x] création du bloc, du CD
     - [x] mise du CD dans le jukebox
     - [x] Aucune musique jouée

- [x] solarmana bugs ?
     - [x] Les blocs sensés régénérer de la mana comme le bloc de mithril / bloc de minerai de mithril, ne régénèrent rien => [Le mithril n'est pas dans la liste, le reste fonctionne bien](https://github.com/Ombridride/minetest-minetestforfun-server/blob/master/mods/solarmana/init.lua#L32)
     - [x] Le soleil régénère bien 3 par 3 la mana

- [x] mesecons
     - [x] La glue n'est plus craftable à partir de sapling (ajouter craft possible avec fungus, plante inutilisé ?) => [Fonctionne de nouveau](https://github.com/Ombridride/minetest-minetestforfun-server/blob/5c008ce6f694a3ab9743c1f3e9c97e82384848b3/mods/mesecons/mesecons_materials/init.lua#L15)

- [x] Le craft des trap-spikes-minor est maintenant le même que celui du briquet, il y a conflit ! https://github.com/Ombridride/minetest-minetestforfun-server/commit/f19fdfc46c536d12e8246da73bda60aff3f5dd7a

- [x] La commande _/timeonline_ fait crasher le serveur, logs here : http://zerobin.qbuissondebon.info/?8c41e853bf43f230#O4113O//33DmlDd8HFoIpCueF6jjx2hqyQMCZvnpzb4=

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/2b937048105bafdc1fb2ab8a8ceb5ec2f08f784e

**Comment by LeMagnesium** [comment]
![Bedrock](https://lut.im/csw5siVc/xKTJEYSU)

Bedrock successfully generated.

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/632b3b2391c6b3c174ff722f2d9aecbbe828b8cc

**Comment by Ombridride** [comment]
For Glue, need to try in-game because of https://github.com/Ombridride/minetest-minetestforfun-server/blob/5c008ce6f694a3ab9743c1f3e9c97e82384848b3/mods/mesecons/mesecons_materials/init.lua#L15 
I think it works

**Comment by crabman77** [comment]
Fixed jukebox play sound now 
https://github.com/Ombridride/minetest-minetestforfun-server/commit/353d954d6e91b58b3928bbe72fcd99fcf03dbcd8

**Comment by crabman77** [comment]
The Jukebox uses soundset for volume but plays music to all players,
I can set my volume at 100% and annoy another player who does not want music.
if several players active the jukebox at the same time, there will be more music.

1) Only admin can active jukebox 
or
2) play only to owner using  "to_player=player:get_player_name()"

**Comment by ObaniGemini** [comment]
Can't we set a zone, as for monsters?

**Comment by Ombridride** [comment]
An area of 16x16 or 8x8 should be great, i think

**Comment by ObaniGemini** [comment]
Mybe should the volume be changed not with GUI but by clicking on the jukebox with some "controller", or I don't know what. As it there would be five levels ( OFF, 25%, 50%, 75%, 100% ). That you could just change by clicking on the jukebox  ( as for repeaters in mesecons or for desk lamps in home decor )

**Comment by Ombridride** [comment]
@LeMagnesium 
Can you add the 16 nodes range for the sounds of the jukebox, and add a "if pushed with hand, increase volume of 25%" like the vanessae homedecor lamps ? Maybe also debug the jukebox, i don't know if it works for now...

The volume feature isn't hte priority, if you can't/don't know how to do that quickly, we will open an another issue about that.

This issue needs to be closed ;)

**Comment by Ombridride** [comment]
The jukebox is debugged, now closed the issue
