### ISSUE TITLE
More connected glass

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#95]
Add the conencted glass option to the :
- [x] **moreblocks:super_glow_glass**
- [x] **moreblocks:glow_glass**

Initial report from Obani : 
<Obani> MinetestForFun_ : Il semble que les glow glass et super glow glass n'ont pas les connected glasses

**Comment by LeMagnesium** [comment]
They are connected.
![Connected](https://lut.im/7X5YS3j9/wTdhEQGM)

**Comment by Ombridride** [comment]
I think you didn't know the "connected_glasss" option from the minetest core game, so i will explain you in an easy way.

## Connected_glass :
![Connected_glass](https://camo.githubusercontent.com/d5aad2fad47dc8186cd0508d67ab22f5bbd25398/68747470733a2f2f696d6775722e636f6d2f696b6156614a512e706e67)

## NOT Connected_glass :
![NOT Connected_glass](https://camo.githubusercontent.com/abaf0a1fe596fc22336c119c842c4c80c10132e0/68747470733a2f2f6c75742e696d2f3758355953336a392f775464684551474d)

:dancers: :dancers: :dancers: :dancers: :dancers:

**Comment by LeMagnesium** [comment]
Better?
![Better?](https://lut.im/WadosQFy/mznA154D)

**Comment by Ombridride** [comment]
Year, that's it !

**Comment by Ombridride** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/a090ed716866dc346f14a07c018669e8a7068953
