### ISSUE TITLE
New Tools Textures

### ISSUE THREAD

**Issue by Ombridride** [Ombridride/minetest-minetestforfun-server#96]
I will change the textures of each tools soon.
With a base containing this textures https://github.com/cornernote/minetest-skyblock/tree/master/skyblock/texturepack

Better because 32px and more detailed...

Like this, I think :
- Small details and size tools (mainly from *MT_Game* textures) for Wood and Stone
- Medium details and size tools(mainly from *Skyblock*  textures) for Steel and Bronze
- Big details and size tools (mainly from *Skyblock* textures) for Silver / Gold / Mese / Nyan / Diamond
- Special details and size tools (from *Big detailled* textures) for Mithril

The ultimate classes tools will have also specials textures :
- [x] Dungeon Master's Blood Sword => for Warriors
- [x] Minotaur's Horn Bow => for Hunters
- [x] Books => for Wizards (already done)

It's My work for the moment, i will ask help if i need it :)

Axe https://github.com/Ombridride/minetest-minetestforfun-server/commit/e8e78b0242f0cf6227cfeb34e0aa3a6550107118 https://github.com/Ombridride/minetest-minetestforfun-server/commit/1e414a38746fcfb6b157b8f458ebbc696e9e0aa2 :
- [x] Wood
- [x] Stone
- [x] Steel
- [x] Bronze
- [x] Silver
- [x] Gold
- [x] Mese
- [x] Nyan
- [x] Diamond
- [x] Mithril

Pickaxe https://github.com/Ombridride/minetest-minetestforfun-server/commit/4629f11a3df0b248a3d12245eabb20cbd8d5a43b :
- [x] Wood
- [x] Stone
- [x] Steel
- [x] Bronze
- [x] Silver
- [x] Gold
- [x] Mese
- [x] Nyan
- [x] Diamond
- [x] Mithril

Shovel https://github.com/Ombridride/minetest-minetestforfun-server/commit/c7e8162f076d1bda471d236dc8d1b0a7e7150e14 :
- [x] Wood
- [x] Stone
- [x] Steel
- [x] Bronze
- [x] Silver
- [x] Gold
- [x] Mese
- [x] Nyan
- [x] Diamond
- [x] Mithril

Sword https://github.com/Ombridride/minetest-minetestforfun-server/commit/801264a3d6392e8789c6e982dfba0e28413381f2 :
- [x] Wood
- [x] Stone
- [x] Steel
- [x] Bronze
- [x] Silver
- [x] Gold
- [x] Mese
- [x] Nyan
- [x] Diamond
- [x] Mithril
- [x] DM's Blood (https://github.com/Ombridride/minetest-minetestforfun-server/commit/18253658d5631edd8b400d82fca02bfa6cffdebb)

**Comment by Ombridride** [comment]
@Ataron wants to do the  __Minotaur's Horn Bow__, the last texture is for him :)

**Comment by Ombridride** [comment]
The sword textures will be modified soon, and will be more different ;)

**Comment by Ombridride** [comment]
gold sword and mese sword neds to be tweaked

**Comment by ObaniGemini** [comment]
Horn bow texture made.

**Comment by Ombridride** [comment]
I uncheck the box for minotaur horn bow :
The bow needs 2 texture, one without arrow and one throwing arrow, the second point in your texture isn't placed at the right place, and your bow have a cross to large

**Comment by Ombridride** [comment]
Every textures of this issue are made and added to the server, so i closed this issue !
