### ISSUE TITLE
Flint and steel

### ISSUE THREAD

**Issue by mgl512** [Ombridride/minetest-minetestforfun-server#97]
Pas vraiment un problème mais j'ai vu la recette de "flint and steel" passer plusieurs fois dans le depôt ces derniers jours. 

Le "flint and steel", c'est un clou et un silex. En acier au carbone en opposition à l'acier inoxydable qui ne produirait pas d'étincelle. La pièce en métal a pris une forme pratique de anse de tiroir de meuble dans laquelle toute la main passe. On 'enfile comme un coup de poing américain, pour qu'elle couvre les doigts. L'autre main reste immobile et tient le silex juste au dessus de la troisème pièce essentielle du "flint and steel" : un amadou extrêmement sensible qu'on ne peut normalement pas simplement ramassser dans la nature mais qu'on doit fabriquer. Aujourd'hui, c'est du charcloth (ou charred cloth), du tissu carbonisé. Les pionniers américains utilisaient des "charred plants". La main qui tient le "steel" percute celle qui tient le silex par rotation, le but étant d'effleurer le caillou avec le plus de longueur possible de métal, pour obtenir une pluie d'étincelles. Les trois composants tiennent dans une boite de cirage en métal. le charcloth est un carré de tissu en fibre naturelle (genre 100% coton) de quelques centimètres de côté très noir et fragile. On l'obtient en plaçant au feu (ou sur une gazinière) des carrés de tissu découpés et répartis dans un plat avec couvercle. Ce plat étant, la plupart du temps, la boite de cirage percée d'un trou citée plus haut. 

Le charcloth est essentiel parce que les quelques étincelles du flint and steel n'enflammeraient rien d'autre. Il est renouvelable une fois qu'on a un feu, il suffit de sacrifier un petit carré de tissu mais il est essentiel d'en avoir au départ. Une fois qu'il a capturé une étincelle, il se comporte comme une braise et peut enflammer un amadou classique, ce qui permet d'obtenir enfin ... une flamme d'allumette. Donc si la recette doit être modifiée, il est plus "réaliste" d'intégrer le charcloth dedans plutôt que de doubler l'un des autres composants. On peut le symboliser par une laine noire par exemple, ou par une laine quelconque (ou un fil de coton) plus un morceau de charbon.

**Comment by LeMagnesium** [comment]
On devrait implémenter ça, ça serait plus intéressant. Ça donnerait une utilité au `pebbles`. Imaginez: Vous devez récupérer une pebble, la placer, passer un tissue métallique par dessus, puis attendre, et la pebble vous reviendra avec à sa place sur la map un trap_fire. Charmant?

**Comment by Ombridride** [comment]
c'est une bonne idée, je ne savais pas tout cela pour le flint and steel, pour moi c'était une sorte de briquet du moyen âge, pour dire :D

Feu vert donc pour modifier le craft, faite comme vous le sentez, je n'ai pas assez de connaissance au sujet de cet outil pour réellement juger :)

**Comment by Ombridride** [comment]
Il faut nous mettre d'accord, le craft doit être composé de quoi ?

Actuellement le craft est le suivant :
```
-- CRAFTS
minetest.register_craft({
	output = 'fake_fire:flint_and_steel',
	recipe = {
		{"default:obsidian_shard"},
		{"default:steel_ingot"},
		{"default:steel_ingot"}
	}
	-- /MFF (Mg|06/24/2015)
})
```

**Comment by mgl512** [comment]
Pour le craft, ça:
```
minetest.register_craft({
	type = "shapeless",
	output = 'fake_fire:flint_and_steel',
	recipe = {
		"default:obsidian_shard",
		"default:steel_ingot",
		"default:coal_lump",
		"group:wool"
	}
})
```
C'est suffisamment varié pour être "shapeless" je pense. 

Sans un amadou "charred" (coal + wool ici), le flint and steel serait un briquet d'aujourd'hui qui n'a plus de gaz. C'est bien plus durable qu'un briquet, il peut se transmettre à la génération suivante. 

J'aime bien l'idée de Mg.

**Comment by Ombridride** [comment]
Le craft me plait, plus qu'a le modifier donc; à moins qu'il y est encore une modification

**Comment by Ombridride** [comment]
Puisqu'aucun retour ou demande supplémentaire,

Modifié ! https://github.com/Ombridride/minetest-minetestforfun-server/commit/7ce665ea0d21f1088fb03509738051f0c1d106a3
